import subprocess

import requests, re, time
import pandas as pd

BASE = "https://rest.uniprot.org/uniprotkb/search"


def fetch_uniprot(query, fields="accession,sequence,length", max_records=3000):
    params = {"query": query, "format": "tsv", "fields": fields, "size": 500}
    url, rows, first = BASE, [], True
    while url and len(rows) < max_records:
        r = requests.get(url, params=params if first else None, timeout=60)
        r.raise_for_status()
        first = False
        lines = r.text.strip().split("\n")
        header, data = lines[0].split("\t"), lines[1:]
        rows += [dict(zip(header, ln.split("\t"))) for ln in data if ln]
        m = re.search(r'<([^>]+)>;\s*rel="next"', r.headers.get("Link", ""))
        url = m.group(1) if m else None
        time.sleep(0.3)
    df = pd.DataFrame(rows[:max_records])
    df.columns = df.columns.str.lower()
    return df


import gzip, base64, hashlib, io
import pandas as pd

PUBLISHED_MD5 = "0c1ce4da5e0b8282b883436ec33fb8c6"
REBUILD_FROM_UNIPROT = False

_BENCHMARK_B64 = """
H4sIAJGjxGoC/5S9yY7supYsOM9vycHLTyDYiSBFsAMFDasKOXsooFCo/y+zRcld7hH7nJ3n3t1HuMvJ1Zit9v/97//n//vv//v/+u///N//x//5
3//7P9rUpwollaDP//yv/9jjbKXPiD/aqOMMsUUf5z7x51ziFmus/j//13+4VPakfFKq77PENHUKI0aNl/AK3+xt1274qM8xq+66H2Xq0TK+1Y/D
mOCrD75NdR7TR7X7vHczc1W9hdxijBtfySR8l7dDO++HzqN4PbVaL4VXUrmVeYZSSitlKy3he5TuTXmb9Rm7b1obn04d1TnnwF8VfBc+8e5jr9vW
XdGhm5Z0z1bPaK33x1D+1Ftqp266RsVP1IyO3fQtus0r7boZWas8dR3Wu9HwKY0Pm950iEZOQIfSnbd4VNd5Enr4oOMxnRs9ul23Ng8fDQ8juB5x
kDGmmFMK3afYcSJ2+t3M2fCNJiivY4h4Pbx2SD6m1IfC4aee+ZF31U1KWhcckmnObBbfVnxRavZhq8N7tT12NUvC3TS+bQ++KxejwgGrGAOuAL8N
Sn7BSx59hBnTCLoMPNCOr9HW96DGHnA52kS8SMop+oRXmaqnNPhw+cBLJqPw9ZOP5sNuBj+ZijjX6FWq+NIcVdcxdV+1PP5Ixo0RS1JphnPvc6aU
9unxwMn1vsQtBNUnXnjiwILTKvQlbrsyPWuvfcdram8gaxDdfOZotcn4g+/3z1nzxFNvkE2Pj2cajmHHkXv5h3D4oVI8+E+JMu13VSHUlSJgdeu1
R5ymT3ouEeiQ+mE3h4OnCJytaafHkgE81hi+QbOOFPyYww98OI/fB+dO30++be+Jb3x6XVyuZ9Vb33T0ofkzeoghDszFOvC5qJt4nB6Vr5MigINQ
wSuFv58mFnO2wv+VvPMrYyj4R1wVDh1fhmtqamac4FCbmedwLpYYmyhZigaXyiuykBgKo5rQQddLLfzomy2iztMFqMsYc3qcZ8wRloP6HB3Ou3So
dffQ1tyhI9FUHVqyXsXNd53PmIramoaROUWMPZ89pI7n6wGynVTGD5wl/22G5zv2zncc1zuK+O4jmDbOEtyY7UhjbvjmWcbsDocautqrC1VMhMV1
BFUg+LjzgZPSOpemDt37qXLUvAB8V8aJ4Imog9QsA3WEzuFDiYga3LXHd9IQuBSth2LEppo3eTfm1NnHoY0uLZcNeroZ2hlar/C79cp8tB1PHGEJ
+gaLpfC7sZ1xDmhkmdFE4/sR97LBHkZIkj35LTbtUAmF07Tq7MGZkqaZ+JZQZnLQHwVthxGd3vEtvAt9TN7tyFNBCoMZgWZ9eH8Zk4EfCSpObcUL
UJlhi/BQU8HU75bvOq2aJ2Qb6tUs9Sb1MJpJTZcTihVDgmVtJc6CjwN5o21oRbmAv/O0FGcyFHeFj3YWPLPFB7dT25RL1sYmZbbgXcVnqg3KUSZv
DkcMsYpyMXhjowzkTGlTbT6gcVPP4vAIVlfoM58e2gUDKhK/mRRaE/ne+dQ4Xf63QTLhXBp+wTfRxjW1pbnhn5SC9op7aId29IrNO/wUdeOLmJY7
HrbVMvHUbfR08tzSVNDGQCt1OkdtgIjYP/sKPJyGXauN3uKyFDChsPTRT1hT/DsvCjbSVkogbKRc1NnhjFL1Lms4hX76VEagQPo0YJhOmKA+Tvg7
nB++vG/V6NOqtEUNo7H1WBzs4o6H2nWqlWqNS7fpGHQsPDIaFeqhOJReVYFZHhDol5LhxQY+KpTMQckgaaJkTSR5RJ9Vxtl0+XLHLw/UydeXh9Ff
OvkwjZOmUeEA/2QakxspiGbinyO+FkYKv/oETcAthpFFQXWr+HzOlzTchCnOI1IinIfxbXj3bUkF3mO7xCK57dQV/yvFQ8JgxKqLkFqKQI3QvwhX
eorr6SmUCCfsYT8TtYmX5pRJjudmXIi9UWKBYEKGHCU4f+eK2C4gHbvPBJBge9LLk80pwAkessD2aTUv4AQB9iF0vF5MvMUddzxwt97RKEFaR4Fz
xUFB41qillWPuzsK3oqPvT5u/P3jUll8ww3iipUICaBOylCXMyVfNhVM3lp3m4m8ODEeMM8pxhNmDLK5TZHV26TFQWwX6Qpw6RN6lcWCdIVT2iFM
TiSp0FXEU5tyWFgf+AJcae7xDBBeG5f44yQ8fHvc4HZhd2DNYLbl23H77xMAHMHtJup5vk9gTwPKJ1/h+BWEEPdXVPkK6LE/gYcCvSO8In5OLU1Y
Ymh36nDlqmUN6ObwcAB+kw+14wMBUkB3o65mEFdAjXWGWkGB4Yp8oYsDLIwipckEnBRw25STiyXTIAIIxwc03RVMSylArV11pdTQdG0qD6V3/Avs
Uoc4wg4NcR8TgocXdYBcPP1tZrFmKp37xDEcE6KgaQGjbbvv1saqqjXFm2qoO/jMdQwNbzC0JYSs0CDYgK6rN/grrZaC9ZAaFcwBXUDxokkjJj8N
bBtdYKzLSCn6Vrw7IEUCYITdhCypIraE8AxfQKGGLEF6dbqFWqUjjh2fI1HTk0imgkFQMAKhV08A4wEceoaTtDsurW+h2VbbeahqcoIAu2R5zPsB
hwCvAscD22vhKs/QxZUCvwMSa5wY+ETLKWe3AcD43cMk2HWcDiArmboDZMH6VsiSb50gC549AeoCYZxtiTD0fQPUhb7DzEEqBZMAOnjdzh3OXM9q
jAHg3oAcSZBAMdRhFJEqPy/vDYpZgSD9nHVzuJ7qa7GdpkqP4k4HGEJ3AasSIQga6GSHIsFB6HIAF6ttA6ZdDKFoRTB04DfAkTABgr8M0VDKYndm
mmfH/UEs/KETPlcYJ5hJ2u144OeYRP15K9bADzW409HsQf313fg5Tjg5nV1XtdoKpc1hBLXtpB54n9iGq2CHCcre+gaModoOEJV9AyhV9KIRh9oA
yC69uHDcKbZwTHny/sZxne8KTw7zmmoDLTIdKAp+M8CzZdyNlwPYDRgpJJBAhuzHdEFnQ1yjp4rVOp8kEIgvt+x1LYYnD/XuJHXRFn9M8ju5aE8O
C+kvkGodcGdt8VeRlAzRFElpnUiCgqK8EzROQRFdBHODPSbqwqfHnUFjPMQkmgzHmOTZnTMCqiAJoWUIfrjUJdD+98vfBgfdPChtiu4TPGufZG3Z
4/lBAIkroMkgIMAV8Y0rQEDasNmVBpHJYLTT4jOc2jZBFg+1dF9qiX9Ksy2/ihudwqfa0nQo/2WPJ+3xFHssWhACsFnyoGbwDBQlUkf5ADD5TYNW
QHtmSOK25ihj74CbMKJtmzCFG641wn9AYC6rSdxzoW684kLdc93rBo2DOYWY45BjTS3sDSxzWdKJu1IZL5r9no0Cmye59Gew2UDtwMoUTEjOsKkR
EAHvFpzfQyHI8ASJ7rLbsAMRvgbOGf+H9IYJ3ak0SvsBaUwahsqfNFgeb90g+723mKogRRw/zJYGyi20Cl2UBAzbA2wlkvRuA0MYQJ+0tXvLwOrw
aLnssNYWGA/g20PQoVEwhpvVec/jqPBlMAniops5Elmc5y8RrB6+YNnPUeWyDgtXCFycbeKjT+vFgbmtdHERpZ50hDh3gHz/tm8KUGXizOcmnCt1
Bx3CUcC5Ae4zIgCS4eQTATWkCQ8MOCd4N/g8K74IjmcaC9e4A3MF64O2Bf+4vEpcuM1HYIGNsI3M7GUEd/hLYJFjdqqPA3V8i7yjYYB1ssSzcJUn
bBXZNWiW7rWAciTdslhPWqSzli0PnDD402WRYEVh2yAcGZoLiwRIpoClzshLrzCvGwybQCYQwgTJiLjcOaYtlwHHNVGy3w7LvR2W5/MPkJijpkI3
aOuZujzMCMHhjPbB0IyCeipIRoTFNC43WyaIHJTJAgUDP/OYAJaaWEjoHOFUIc81rZD6ZHGeaQMag6aTHoir1Norp3SDkRogACuE9FcYeY8FyByE
kgQI8uDP67C6HBZAbIPbAlWC+SacZTCHLpDBHzFTMCEDZ6EjXxWUEooMn+gP8hRwObgrNa8gEKgEpAxfvPO0gLkyPj0w0XhhofHUYCUanJcGm6XB
ytZbg6NosFD7QOYBXwDpDgrvEBeuch0Kn9tMecLA7E1ngLoSmhoQIVC4kxEQQJ9oe6OATj6jUJ5AwsujBiLzaja8vbEQeDww0HECAIFapYf3G4nH
N1+ydnm/fnk/Ob4XbXipGT6qv9DQD+GCNs8lXPdXQFfz+qdsQ65h8l/qdsDnwllf8VeyEXyCU64GshD1huPz8zwcQ7Mavu/0J4ARWDrODoB7igLs
hQAFR4yngk7XwacDVgTlAss9bs91AA4GQH28BSRg+rTZFGrhWVU3zIwEIwCHjGfECFiES4YQ7/yp6ZMaAbEFzz/wy6AO6wIuHk51nNnWDhg6BjGa
o0f6X6/gA+W3QiDgf+M5oTMrCCEq9c2S9+UxkrvCGdC5AllIOncTLeA5bh1uswEO7AekH/ZjQcEdBupntCOtNwpm4gOY3vDh8JKRHqkPeBhd8TT8
cALPJ6+JWscA7QYHFudOpS1mmg32stGQ7Z4vlAz+XY2Oy3Mu5znIB0Ow5ewwgwamFDYfWJuBE/psD4eYFzZoRww4oQDL7GsOzcDGwx8UiAxABQ5q
EFEQe7UO11QIVlrBD7wHRdLzZwmn7Iz9mCEnjOsEQ3qgqCWugB99iasRr3DZV+CcyRDKS+aBZloDKlA0uyLzXRycM+QeAD0qU+JcACCduzo3h58h
Mqf1+bIsINQWLwO31CX2lA+6KPyZgU3Gtn2nFJ9VaGdI32FkD6K2P8PIC07ANaWtp6WxOdhETjhB28H4wHUBehhc7nhqnDHZIfSGcWy8Mxjy9vK5
Ofpob58LuCHYbPncEzKw4e/9pl2BxwwavgS6Q0UxGvcFgwih8eJtfYJHFzEZsHKgLAA5oeI9hx/6TwHyr0/26y3A/g56OfjPr1sAlGY4x2giBcZR
On4NQ4UTnJhRehwP6DJUiXRO8RewUFMdpa6CtvAtG+wojgUMVZse8gkaHkHbx1bw/BZKeAK0A2ziE8EDLrR/R22PFbVVQXhKF7Sfl0lkHEgyGO4y
aElvSgxaTcONkg8/Lsj/S9pge54KhEiubZ/BqPQENl3+D4t7hRDwx5NBuonXSYClYTgIRRvARRSBRIQOR8TwTkwr8GG6gwXeYU3hmehMYYlHojM1
Ue7t5xnu32d4h3McLsZdqTXtNOUPLmUkDfNvWoc9zx2wYMB3wVSJBTpwU4zG8+aWh3Az230+/QPfeQXuMgyx2fEFVKNQAyx93EZRYJoSI5oNfnbo
Fk48s54wEeBYbTRwDsamGwCqBvc6+LHAwwMgWhAURvOt4JbxRelHtkQz7gPaCsEmuRKTCGdFv+D7VjXwPkiq8jugCsx+hhveAFlEUnonCJ9lhc1i
Wuh0h2k8dRwOLrLgVHaJYQuJgSyG7YpOAngYqLDH5dSNMCttejrwRSFpA+ISNHiRMDRzNGo+jOqUwP4BD5/B+E64kjorcA10Bee4YBStEa8SyEB7
vMPOm56HhMFwm3GjoFToU/LtYiFUzAyIskHMqZix7V0gQVyEmPCTRE8J1x+0KRnvyKChZbQFBBR2JdPTC5JRZzJl+HqK+yRgho0eEbRYAyjBlQKp
+k1SmeLLIVNggdHu2sDtTlh/vLeka8dK1zZJ1yoNEfIWXKz0bGif4CwS6EvF1xw6nhIxeuSCxTS5vnBl/RVXivdfpHDD10FF8Gm8aOLht3AA+MQG
nQPr3YBwBrSv3+DBaEgaPPQBChUZSJ2GadQdZ0//uuAeyAQlgyEPCRIpkZp9SY2fBTzAdONBX3H5I1GnDgE+3R8bSKfaPFC/P2iNBfc4a9VObdzj
AyUeQImRKNELSiy4HlsEJe4pQt4PnGEHEu2NwSirgfQgzy5s2zaEBWpmVQCqQICVg23f+h4ZWnR4UYBksRe7VaRQV+amfmZu3DtzA88s1LSCO/hs
1aIpsAgdzrvSKcGWQ2Ko+5W6j1Oxcj6Kd7w7GGBTstxxAenQ0Lt1wzEdK5dTRHlI48OAT4RuO3hcl+rZcI7V2bDANowl43zMhTIDx0RvlGjfbpJx
T70CB4CGUK8gxwDDFUZPXALuUIVJ7gS0VZi2nXfalhoOg+9wtnws2FUV+FCKuB4SFhqOCwZaaB5kPvdcS/jML4Tf8wuMQpAfgOnj8wUi1umn5v3C
3RSaqpbgtGdw8gewSyBEoVQQKjGaUMTuoa5R1U6sk0DfiK46XW0lvsKDgsB4POWKQofPOHUBqw39Haf2K2rlnVLi0aZ4tD7Eo6nlU1g2cDKTaN3R
fYHcMl0EeDKPvkO+WT8hZllnV7s+FIO7MIHhdHgsh0/RK8PTDvqwAFGXQM6kd/sM5DD9CstDzyqBtZV7VVnCX8ngIrbJHMXiIAq+BT9493ghSAsT
8Xbf6zZPjZNqEjhK/PhB4kn4LV4+B9D5luttiAOwV4f0QX7HATHOzAGDAddUoQm+WbVEpmgFTRz6JuO7GHsmpusiSxGQTko9Tjg1+DmnvG3tpDeD
o2/zwGFI1kzjupX2Jbu+Uv/gDICIuLol2Pg7m5hVBLLBkWcNOwJYZ0CYYz8sHo9JvA0+A8Z/h/M+XRa0DA/QHQMzR2T5BjgEyR/McIrm5HEm6xmS
n8XXK8UHpplhUZeBTKxsgNT2TVya9swcFVAVow0FtU/mk8+jRyYcmu3ZAaDsInOOmXD5NLPDUbcViVOMpfXoa5HgFR7nINGfJPVEjXFAckUpmTL5
RVgfSRUfXZ/iDVsnHneCcwA+q4OZB9I1UW7VF/KI3guOteD3XrF2xOIguz7DuXlGpDSLPZQ1OOUdaACKaOEvNDzYKMeKFQm4FyY1Gd+1/iYmUYpR
yFUICg6cV1BC/6A/gxoBVBL7wsjADXBcLs3AYOJJUlvqBMMEnAeGFxcQnxAVhzAdEzxWAtLbKiwYeVQ8+yvrOTe1Sgvcd2kB3DEY8kXU42WTLzoP
m8w6jBEWIOoFrjIJIEonk22QvsWUoz4lkvVmOHgLJU4X9/tZKMNCiyaFFkoKLeT7r0KLuAotYOadFFrMu9DiRktwv1nQktp0SjdaygSQN1oCZMv+
M2refkTNfTjIIztc9YTeMXC/ipAiC4bCCA6wWY20T6DS7MXtjWJqwPWHCPLCqJtleBgy5vf1nRkWhZFhAJQmiXvf4AyCdk8M4x3EHThvPlNVIEJ+
5q9U1Ru+hzd8j+EB3/cBj17eHuW66oEXe3kU9b7qRGdZprAogMEuyUl/SN5+A21QKzc6gUASoA+Tr4J1aG4YXsBf43ewi3v0V/BrsCikN+omtATu
tO1tbEN4dSPEaIToeChGqwiFOrTfr0AcUd/8LtKbMGoBpiutE7vcL7xv7MwzdL8e+pfSmpukJWrAkYtjaBrAv+KhDLxyX+EGAMCqGCxaMbdxxcOy
xMPMO/ZqFit9x8ME/DbXErx9K6AfYSulOLAHx9zebQ/hSJySoNJKw8y04mCKyEJt8Dg1XLGAvrghVK+G73IyN09G1MkzJ9wjDELGJ2nOnRDDeJ/+
kODFZLCHWU2QoQGJGjVUhZfHjVTXTAWc7crIiSfWvDgY7USs1mFcEuxentBwDxs9dQ7N8wBvXBOkYMdA3xItJkmqDd3C2NkOhTXdgnXHuQPA6cF0
rGZujFIDX7F7xjahdALtTggD/ju8/Bz99d/9O/mFyNrE4g4muc+yv0KQ4wpBQhVWddXCkhkufNmrIIIBwW34GLHn5rKndTRj033ANngr5WhGb57Z
WL0DeC9+wPBbdgxOq591fbiodH/BA/Pk8fyiBRoKE/+JFWsw2fylfSYqHnyeaVcWRBYGwMMKgCeYEvCLmWDMvgpowlVAQ7oKqdN55sw8lJdASSEa
wCOZpVaj5wUz36VlnfYfRqH/NAqUhM64EfzvmVixIOWlMGegZOHDnLUWSMl6Lu1tzqh53cO+wnEyqig8zeiUrTcgeoYYsAMMWNC+DsbuJLAqfqzv
hHbQAc/ArF/mLy/z91Ubp+Zdh/OjNg6cJLEWMImF8iE4p/ADULfA8UIfpHZrd2CjFqCySrg4ARuKPcDtppOVA0ZkLbB2kiEUvJeiK3BS3NFIXUGL
YeI0OEYEOQP8wK1EOBegNXCzJrd9FTd2GiyIaqAbXUUTcG2hF9ZJwGuWggdug4SDCamZod8gzafbQqi/hyB59BKCnMqW6CTGO75CVY+SxpgvdvnK
XLuBs2ENaZOcu/jrymox6PhuwfeYtQYAgx9NFqxkZa3/QNnuz6W1PYreNoJ+vSLKUDDQJPBVaFw0+Ftg9QH0Cc9+4FGNHwRngG60b5vOsNr6CAZg
I9lxRtb3QcIYHTpgIO0f47edV8uUj0QO69tGGyMUkjG/Em8KCQMACFXfFLICbpZWfLGLnO6d9acJ9sxGBw4CPYhAUdZGkHK8tx2hVguyP+voqxhw
k2JA9aMY0HwWA7ZXMWCDgbyz34XZ7561Gn/Mfi9I2CExzxpcB//M84c3uQrN5qvQ7MmLYXXCYHG7m0OdixfDF0iIhBGKATYJaA0HBJ5SM86wQJAG
aElsxM2dZZ3b0eQo5iPeDWDATJG6fHgHnonK4Ii84Q0xVpTOCUXG7YO3w1BQ01pcaB++JF3ZcvcjW75S/VJWFuZK9avbkX7GZdUVl82vuCx8HfwR
6zoGc+ER8gRtyyxFBbGqDbD8nBbKXiGPeIa2wn8e1wfvTEYNpD5ZWHUyeQmLK/mjlbpmGB2fUlLXEkbHD0ln4WpwV8BmQGnn4UC2B4wDYOk5WCV2
pazOMs0Vj54MwA7oW2v5zGPHJ4CQFgNnumfGozfoD2ACAOu4svuwLeCKaZmXQQ25zMskq013DcfETcNDAmCl6jrLXUep0W1ADmCVcaWMXuVPSsIi
rOXATUtA5F1G69NdtwfYdBIswEcEJminxAP6XZVmLMTeDt2N3fUMLPW29uxwYtr4wqAf/omi83F3UM537Q+hwpcjcB+OgIYefwfTngHzdviommHJ
S2YMJljW/xvm+iOsqr1ST8sf9hVoLUD5rvr9zXYSQ33tT17m1wpsgVs4q5HJl9voywhFdjC0zIdfUdItMiQsmQCfqillY0QdJxarL8e0+A+G3h+7
cVcODxfBCpTVaND7R3RQghikrRBlIWRRyg76Sb8DEcIHBxA7vZ+riHlrkwWxNHUhwpJNKXwulXWTpwtAoF2QCj5uYtlZh0rACp7Z8l5Bk8NVsBqY
7oFtrUyYApnDt+bNSjFql9DIOywlIurHne3zq64U2OWdm/xMhqoct52vBVXBsUYLSNg0ICxUSW3wT/H0585mhOrDgIc6QfWy/mOtZ7aRQbRn7oa0
YI4xw1vObn7awcElVoRnAvHiUxvY43ch1kGK/lGssqtL4/d6ETO4RL8+F6tEX2X2K0QKzWTQGIdj4SpzNQcrEYnkcZmdoN5Sg3AREoOZUCKIJ4S2
0wrDYrhWlkVLQs3NC+NSBDLgDswZH8T3+dHT0Bk2vm3iSb1L7D3hR7xKtBRzyfAHehTQTkvPuE3gtzu4Gi4OT6z7Wez1o6Oq/d5RRd97uPj2vTGf
ncFm014B+l3vhCPDbFlachqDRZ5xAAejAVieV9W/9I3kCWtxEeAu9m4R4CteIk8FYCoolU+1XYmDoj4yB9a0xSCHhU+uFpY6naPiFmFtgCHCBDdL
81BHK0eS/Pqkpdj4vqyQhkGwYRf9q/lgsR5ww07xx5sDQx3EUFL5t6uqg57GbwKhdmYcgWYyCIC1gDngpbudLJlsvvsjKNhZYJaS4XWnvjhHjG5P
W4M/mWdk7VKHV5ZGAGbba6nFsnh7AlCXpPdzn3ixAf2YpcghQ/+kdsUzaO1Zm0b10ycrX9QVYyDm2Qh7wOhAWEGEFuyxYwPsKUTPgD0GsGdh/VU4
ygYGw0qIeBWO7lEKR91wkvUc7iGVaXxkUAWW4qBIA/AVkMJsWdYIhNjzksIpAc1zdg1F8KrhWs/uAYYgHefJ6kq2CUB9BsUqrxJz+DjwuOkYZQ1n
CAB51LU8AJn2JqkIz1vCIehYwVrBRCxuaVdAk1oQ6VUqMuqrVCRa0IW+ao5UwvtSTKoFZOqAVP+IjoEoroSGmAu4h50MUMJ+tTPZKWG/vuI4W684
tdHN2SObTIhnDd77SEC5lN6CkwJRv7phYLcWhILAQk9XFhrABUax3GB2hTWkdAy6TMicGJphJQVjIWOFNRiaWeFq1hP6gvdLLC9MEmEAQjMgu7sd
cPJW7R7uBqimsWInsUetM5owdP7Zy7T6Jn71pHOF8lINrMsK2dzhPLXTpjD8V/0rmofHNWfGzcOzQBtadOD1wbcDVGCsNisYD7wLMJb+jo0yfPId
G/1TUZ/19qpsjkzVd73ByZ+GTY8dBslLdQ/VG+4kMRxvT2icwyVaiTdAKQYeJOqrysevSnq+Pqj8ZJVPv9yEVLV2UBZc8i71Nf/QzGl+b+Z8ZcNz
+y0bDlFnNrwfIoEetgefcfL4caNaAbLNreOdQEMA2thicaFoDarBjhwWd0DqCW+PODrOYpOsdGeD2DyvUCY8GnAaFGY45Td6Qrzt4COU0otIthHJ
hsdj9qmrlmpLUvci+amj5cLSkkCRIqXeL1qu0nFC/Vud687MlEhSnwQeK3KnmB8DXTCs6WdQlZkhf0wchhoOf+cAcXCtRroZ1BwmW7AKOBiVPUjn
2TcD4QGw01s+6Yim2K/pcLlJB4aBOrRBw1CAk1zGS1KKE25otAXZ5tVLAgQEKjDEBT/6hHfV/a8x2iscHz7DMaCIsHiMYsEKWDYRQfoCEHyA2der
4vvZRVo+uki/+pndo5/5yyTEL5Mg9TeeJsEuFg17itdm0yXIB0gPtC4yDgwwujOXgndhagzkVGdrJEgP1wYmARpvdc3QX/B22Ee7z61BO6CFYNa2
1YWnwdKY3cBVzwQvMQXip+lZrWxxTECxOVjHyhB1gmVIEKcPkyL8GrBdWBxXisDIh7cVKXaMZsGuzlWRTjqsFx2epMOJ8KerI5MOA2zvxRwSSgFc
doolV8vZE/uklR2CLB4WpDFbKFg0HTdMZOWYriLyA95ja1CONuPPSq/qG2A4BpnaYFHuirNLvSR/tOnrNpqB46+0kqrCZTCSOZSQEugBqO88AcHA
8GE6HMEijtvgCTJ+WLtsBqvlFHESzEcHmtKq4sarhbUEnmI7905F1qG9KrDenQ/5u/bzjnUr6XyQJNtXv5Wc6QXeWjEAOlU3xQLF9gZvXpDnbqIN
W2VR8jbTVvcE5wvRAKUIewFwHJmMbaQteDEFuO4BPcnpszXRARMxJrq/WhO1Noc5tNmCHsSNNPoWjtzYARsftrzljL8HfNDgI+VUAHR2Z4iUjdXw
ZHdC9vfyI7nzvfsTdxOKYXXUmcAvuiJviQxuCJNn/QuwV64zbxBreA+vhlEnQARLSO3IOCKAhR3u0kuwYQcHLCF/9RYuK8As6nhbgXBIiGIBt1Wx
UyvLLpiYZJOvDSu1Ea7UhoLNtLApVVUWA3u/wv1gqq0z3Q+P1mBRIda9uivYHJn48uyZDhShyIzPatgP0rA/nw377xhcvADFvvIkVSqDGnMT4MCq
iuzYdh3y3TO1/yxBl9IjkBabASab9wyudeAMiKfaGcdlNALPNgMs+xnOMValYwdehRJYg89sIYPxPMEL2nayumqw40oqoyW8CEvMDr8+84EXHFtV
rgEUAPVLWeOT1JyL1Nx1R+Wr8IhaUptW/YB/OlnJ707GUln4pneNK+8rnrQFFmHs8AJwo8dH03/+bvqH3bQsKzYVb1iyKvkkGCYwZoF5wwfXC55l
9c5ANPY5S6EVq7NwCJY/4YdSZNWgIwMw0JV9xWPDBxpnn+pn3MwdcGhOOPqcqsCLMuZwAOhGKU9QReL2EXbHm3Qwdzk4pAEkfXQOqDhKlhDX9hVh
YrWdV/nRYLdXk2yAJQtOsarWnRAH4Ky5wxzFDjZzplU0xWdaGA3QoIGKdnJxmWEAyyGNvbCZdoIbfOa4w5Xj6MupTtV+KYWckkvt44NKAt4HljfE
wCqhsQJmr7kW4TXXIv/TXAs2jIeExyKIpLbCe+euawXEh/BsDK6nDKo65ur8+JHvB1ioAfAlGjBRfwVNf51tEF+zDV4FSoyBfiKCVxMwbJJgrpkh
juyN+oQH8hIOGk0pKPCugD535NU1My/C4Ug4APWCyuGqV8DX7juOFQ4ZbhbwwR9SolUNgMPJ4qAyWaEB3+qITVKwnMvgisEVu+Juc/TVPRte3bPQ
vMCubPWHrmz/YTlzPJs9JKp6ld85xXDVyjl/Z+O2VV1rYZ92+OHBoEaXvhHP2SLXaIef5UVwN7HARpsK9UtbPNkVrBqDCRA8IAmilp5GOS5gsqJm
szOIl6Y0fChT6gZ/2bc0cRZnmuBUQPPuhOlhD1SFNWmFKdmZLEwDP1AB6SgAaaeFlZmgAxPP5Cc7TfEHuH8bCbSb9YCP03wikbgKEINag20Y9pJu
HWl+ZrfOIkgHGc3PZixPNnoVgU8pAgf0fxSBx9fEAZKJtuosWAEP9CIqxCJXaNCSKbYsMupJLKC2XQin2+ljYsSHidFehahgH6D/mUWUrdWrN0Vd
LItpy7vUdV6vvZdXG8GUrKVqs6/JCdJG0FZpdoeVM2RnStSKRWR9sfKrkA2yQ9SzImcnWcJHufyQcnn3XS4v/c3Qemg6qSmOttylU5NnQN0BWVmv
zyRkWCoHG8wY5FI5KGhh47RUeUmHopRFTy+FOHFj2jl9VCZLGY65KpMdj3lKj9Eu7Rv0s/5/5GefMebxe4y5GEgJHiivoHuW+RuLEkVzuihlybRT
IA64yVitWpXsuQvoCGfaCytsOA2kg8JDC9iL1X2Bf/crYMuCqdUVFlmdSy8K23O3GGXAi59FdV4Jka8DFpf5TagQ+Rss2slmXOigwi8KgBAqo1eV
oRMn+I/dO5wJhZumxdGxDxYz240Cs/tkJAIGqruMOuySp0lnnUnAB8PjVXzCobrqxk68PHvmvHqNHwrX+KG8WoHv6QTvdrqHgtZnZ07mncwJ3FAK
PpUFsNHtqrZ9D+SYfxjIQXBZD1Coze1S0X53aUurM1vHHwHlFZJWgMRZKhTmNHAH/Rq+E4QSSqkQRRomnJ/FrgSzhN2utuh32E14VNvi5LVAkUVR
wveF9+268M6eVH2MyIp9Cr90J3xOagD8xdEBk7I0rWRwAM3kF96rj4JLYrlC7bx0MU9011Nso8TqHrB7U+qG3atOauv2GaNjvjReMbrMsMGfa0jo
C2FY8PgG7wZgMgfbRVmFMCB36RiKfc1sfBymHMZsRhgU8Pyqa4CGsjfbwfc7+OKCA1UCDN4jk47S8i4emeDKDkkZFAqaHWCXPWebm6+FEdQU1JMr
j8WVzdU5qPzqHIw/OgfH+D1X9rOk0AkxZhTNOKYYJzXeD3HmcLEdwO1dnIITuYoTw3qlhzff+4315gvrhR9Y7wqgJPH/psDusAt64Xt+hjZg4dtW
jK6BLdcrPw0dzqUxwEAKEy+KNhu+IfJ72tZwy1dCGwrBAUY1thOc6op+QVJJsXy/EkVq9YpWmooSDaQSFnCWeS7FYXWKgGOKiQdVc2k1In63/JjV
pX51BjFdqdJ3y/Ngy/OTxPyWA+n9SWJ22PE23F9cYBs6MJI8tbtSOm5ntwCIF1M6IDtsumhjZY2mfJGFCDM6KuFna2OhQ2V9jfSK4xd3wFWfFGEl
bQkDLtQrA+usFCdHwDQMDvUotpC5nbplqsGpazz2Y2hwJTyDtjCsGlwWxjAGa68+7Ydz9eJcwQoXAQQQhA2b5pARYvB2wONwIkkNT8B89PiK+RbN
WROM+bIIFQACF79KrGCjGauidwhpzaHZHQ1D0O6NoCV2vq6wr8KhqwHN6m45uu1qQIu9b4Vho1meDWgg8NLH5T77uICQCivLiiQBFH7gj/i9KWSJ
hWlvsWSQ2oBju2fW/TG1vTTmcdtfDV4ZRgjQE7BMn6q2rfdiU4Idhy2AhFmJoi9S63+LQWaWtuGyOhzuopeDkQsyQqCcuXvO3pNUMr2F4ww/Nmf4
6SL+1BbJA8nkN7FGAZ8LEjMvsEgSIs1qHOdnbGbhfV3uIczU8E9XlkT6UlhPIM413SXYIijgk4oZaj4tKDscgJUSPLbRk32DfY580sNnJZUaUjm4
4QrdAbyjD23tjxkErEzMVxMre2fY8k21ZM06Ywf4I0yLbyCidWPXXYUhBziXYBk+TO4spQH5AFjJEYx+JHbaRzwIZ5KdLLC4DHdk8VNq+MvGDKE5
t1+ozep9NXduHjLjZAIHebkrEyZia7jX1eik5sEeVh7xBiHG2x7pCgDsMTBVs0d4whztXkmQQYo6CU7dcVQqxDo57SnGwzPjYODqNZwT0FdnMv+s
VlcmDHF3Gyfk6N0x5X7P7vm+lN/K39JV/oZbv8rfrpBUZlHYleOSioy46MIdztwYkoKofIVM01fI9LhCpvMjZPpZaDz6FT15d4NeOXo7JAV4186z
TNte5dRX+4qqP+aQ/J6irZKilb4yAijpTsBnNvAvgBBpdSewjmqfH3VU49EHzXqgWSEHBt7tKkJQqwhhktDBMvrVwOrd9ZDsNpZe4l11G5hyh6mW
0Rt8f88+KrijGi9oouCA2MjAwgJA98HpIieBTC0dmAkoxVkwOPnqBqIBVJ+rBTODcWErh6JJogUA7D7mnBwJdkRoHlPXZ+4lbQ4GfDAWLa1MrJ0I
itNl9jk5XYb0iKM2FjoJwWrnurbBRuM5IsETIhYWpfF/IDPeH42Rmh3UKVwtG3ksEnj98As73H0b5SrqZsieVXUim/gAZUCb2tECazUEN89ngRNO
Wb1HBO1yBqqdTcvwzQatOEnXyUkjJ77VgT+pnf/Ov00y44/wzoMGwXH4xskAivW1LDcVNOvpOtR2J5gdo0NJJlDAKneBPY8E86pMZ14ou2Wu8QHX
nCAX+9EdC0IYiYSFy3C9InnsX4dfWKVIC/72Z4o6PlPUC07ChjBYLyTm2DlAagsrl1zg4fHU1HkguhGZ1uK0JsbkcUV4bI0jo5IeDHZ+DwzZlPG7
A6o+ITrJV/a+4zk2cEfF9kzv+86ZG9kWmWLi8YvmGBZw8CDJUXjsr1ZhSY7uRMY9Ok41dMrmI3uKa2CbBvBckhBIxVNsoHRhDfO76dmQhN9Nz6Ze
ISfYy8GJNJxwyfIS8AGobx54H5CwsAUIN5tjmMp4tarkjwFP9dWq0uIihLmtQWz1MR4Kdv2rJHJ+FVrspQLwpX0nu9ekHdrNY58yEsgDMlS86ZjQ
5MEk21w1kexjlcGsitZKhXueaToqqTzEwgDMSlwoCP1jXwkn8LIm9NVXclnnVRcng0ag9nvDcbFeLnCUZXoEc7S/SoLAtMHh4HYhF4H891EStFt8
v8yvVP8yv5LpPtaj5TVD4Xr2/PPZYTN2mYs4PuYi/nvyM38lPz+4WJFGJI3DYPPRptOaccPSTJOq2s1g7oLDlYlDe51QlantyYqKOZOWWW97Ukwr
seZExmoNPXfXvw3fmH/dnPVbp51dnXb+q6XsY+rBMvnSZgcsC0TJKQdsOoEnY91aYI4WiM1L4VFa07XS93Qt8JOX8y16wjgu57s/nG8hzsRjr1bM
DOTO8YLEwhp4jtMPjbOwhDg0vMPhf4v2lZ/Rvh3QfweBPudOLgKM50jO2DRvGxMOgv85ezMu/M+aj96uoo/XjBR2aiVOWvUx9AWOPtp41M82nqtl
knCgS7kfeAxT3TawjZ7FjLB7UvwCZLh62TpQI6tfiKPeeHReeNR/4VF14dFxdYeYggPcJOoQCvsaHIsHDtM5MND1TLJ85ZQCmGKR1Hi6h17L6BIi
GOblhUTAzPZz/KGR8CNn+fQx6fYxVwbhETlWv0SOv1DWHXZ6oywJt+d9WJhWZyLBL6vU6qNKzVZcJV5EVOddl2zedcmug2++65LlZT2xCPyK3xSH
mmsJztvKHPgZKIxq7Enr4wzAMvb+lPyYDDPo5Nz9CX+rBJO88qsSDOitvyp+ZEw3HSYsi+IICc6eu1NcjmWbkxhOz7uRLO16bCUZoAqSDHzSni38
436w2ietfOs+Vinx6uNky3OS0QXX6Mv0HH05NvfOzLECc8Zkd9bBJ20y5532lQNjQeznJJmwXwWxa3rbM2g4whrtKD2d12htTp20LB7EPyh8hUyd
TCweBDk/Kcev0Okfenkk5gXOs4ZFOGmU4vRQ2rHJalu2sZl3IxuAfobL8atbNh4ujj1yMh4xiq0gZ3h3+7MRnDxW9XYL7Z32+q1VgSXZf7SmP5qB
725gdaFKFhf+jJhKrWGrzjrcrOq5M1HGFmefYT6OJbItc55cIZLUa0YS7WoQ9AgcOfnrOcaA7LZrAoXD++5vvXwPnadNnwz4pWE6HFk3yW3WJmvc
aa5WEX7uvwr7sUcX3h9OOHKY+erTDbBtQHu0V03PPAJgnxT2/RUXC08u9jcxgfQZEzhZeY83hCFkUop4orCJsnUx8JAXCCIQ9T0v0/06LzO95mV+
N0MDHmmG/ECYgYd1uNxtkDEpgbaUI1IiYwNnXOWMNO2g0gAGZ7O4N7ZdhuZnc8VpPN0yJjJ89VWdIpq8qlPUlXzM+GQAoLg3y3m5aVPz5FSbDoPP
oVr0U2rugeXM7lFLvozSo8d7rHF3YIysKr3ztQBlxO8DcgNmhftlvhbIQ5T01zRdH3Xxbk7gkzRdvNN0HO74Wz7RA/8eEBOOUCN71RwrDpuht1EO
Ti1u2rBEFezEmvfAnas5AtgqAxaGEMq26wMSvbLlnEVdrCfG4B1w/ERqANbkvzDceLc1mdG4OiJTKkzksF9fA0Mc8YAdK724r+F3Ho5vdZ6qSu0D
eBY7XtNdCy4jOySJnqSUQqZi91cf8Dp/nrv97LPP0mcvpRa/RkQjbOsVEI1GZjsOwB2GceojjBOvcZRKxlHOX8dRctpwkllli8rKaJwpnQyscaA7
wrmBC4H1qJ3WapWJ9zJ+fbDvUC0OkUFtFXcYN6ChIZPfON21hijoD1d+nlAe0Jl7TQvn/sSm7abZeo+viPOAEEBtH6HrsgDdx2i4C+V5/wJ5JPOJ
m0IUq/IAtFmW4e3eEufvs3471dWGNl1lXVsI2zZ9dmQnfZvuo5QifltL7+YvU3Bf2OW8Bxsr8X79Xiyxj8pI7+BImI53sr5uydkCg9xgVFg/wbif
FDPzBnuSGbr72CXKoWBKD3XfINRbuOdcxaYFcEDjlWE2hfCBVA/yhAGZkM0qnA1Nz4TPWAbsCbg3X4dvMiQsCsjKGQ0wUTpvzSROptBVvUO8UhEC
lbqx3CExmx8jdQS31OG2E0T2GPLBIV8gTsGydDFkZ0EUwBz2sEYa+ALTwuEdkwN7koRfgQdKOADLnLSfB7lXKeJMd0/jvHoalfQ0Rpn1k6XnHzp5
DTMbHwPhTHwNM3uOO0zvcYcxrE59mVSeikwqT5uUS/w2sNj8y8Di/oSzj1nXNzH/LxlkVQHK2SWDR2Afzqm0PeJZDo75TDIgZ2agkzija3QyTr/W
HcTf1h3gZ9wwi2xkX4pfc5nLaisLHyOs+8cDmZX42tpe8F1EjFEdNsCh4c1Oz5rRczIr22O5xs8sMxL3V3nXqsyqM5Oex68aTrLF/YOeGxBg6DIj
QnD2QJzgIVz+E+YGYOcZq4M71k2II8mUBghas9vGa3bbzpkvnesk3NmDDKIRRAjw4AAae40GJmWVe9AmyN0mudsiRT9jZMd/6Swz9ZKA5F4Cbhup
xtvYO17YSBqI8+Cv5gXwGlBNCAH0EMT8ZLV2Hu5sLM+uP8alFDByVR3Y5Qcjl2q5veGKR7JbtHg1UI6VHmp5sB+0cmsBXgTGfWPI006artxtCpnj
B6V0JhslVZEhFntXRbL7+NeqSAbTB6fQMY+1v70SPdIQb7S/R/R9fIzOwIJNJ1zwr4GFckfEviuK8ruzpv46hFWK0/BhWH8gRTbhXWST7qGUQaps
ysHZ5rJhQMzxGuw22WY/rsHqXooxIMIySGXt6PnawzMu4b8rIFniyAno8DcPRZuWo0KAHTlBOqlRBOE6nVPbdU2s/BRZA+jzJmq2akj9I+RYqgBE
MamO4WuGxLNAQL2mQI77rCtEpjGIA1RaNzaJvVAllQ8QxAOxwPQ4yacDPXLmROSDmyxAJkqAAETbRtZgrfLB42DxMvXBTs7Z8xLCkr1LwBT2VBag
2Z4QudPH16Qvpn2U7KLh7ErmJ6Za04rW+Jljk+lpltOnmoeJBxvCpwtO1Xp49hfCxADyG3xjmNJ8kuDvYsMj9J27gqhS4INpjbCFslpYAbCzDacu
dXbUcBAX2izOw+b7DQJcBp96G6bNITgMXq/F0vfT9ZedZqtMbtYcMtI3cSad7NkpC5CxHGa1qYYiviysItU7uYE3JTn7l+SGi8Wfnf3HQAtA466f
YAtEhn8sP8o/yo8kwfwxpPqaIyEpTGn0JlQU7I+b4VA5WiU8VT7Aejb6uoP0HB9+nBaAwx7BEqIc91SKcb3avXJL3qX9BtgM5FA8HneEJU5TvneE
nTgKlpltjTSGa1MWYgLlaGmlgj9A758HR9m3CYkfU7rvz+/2eLIhjfiby5jATMP7XH40wDe1ceQam4hWlA3foQ1wV5Y0EA7dXikgyK8D7ZsSvuN+
myC9IR+7/14d0yPX4E7PCtIOCT6Zrj4DNO5MNpwQvcD0v3QNcXAh9+v5kmXOH9zUCMd0a5BjztpK5x0kQMdrfPMzHvNVKZ0M6xmClk54zh3nAOeg
y6+rZuZ71Qznbv4PplJIQvmvRnHQD+NwcOaGA+0jKPqQzU0NLA6ivZOvWR1LS2G3jM7ypeHO4d0ZCOotmGKl5xh35c/mt95BBnzb7VrZCPAA+w1R
oi8HCmGIgXspXKhwK7XbtZdkLXqRrgLYeojvxPtyKP6y9S5xvsQqsdkZ/8pyZlf5pl2eZQDQpn8o32wBtoQ16mVNv35XBXmpCqp/rgrCp3C9+DUA
+F1e5uOvi8lkVPcT9Kv+TG0u0P9rYPWOUf2GxWQbTfWctVpY/NJBapvZQDdWc+Kfowt9xelZsbeTD6+RMKzYA68yV8kegQ9++PyIPb6YHJcaLCZn
Gb5hERLn1byYXGBHEXdvFHr3l8Zd0L/JSO579tT1sPmPkxOHFPkkNl/VuJ3jmOagY22cURIGlP+YlTnS4QKntY41rVUVcfPPaa2wQzK0IasN5B90
TZwtyxmSwqsWdVoXpGuZ+wjx2eFL8WRikhyH8IMUKejEFGbvGVXz0qset1D/Z/In0VoHvlYUzNNdyRk+2x8row7jjjtUGKrJ+Vv3MFoYgzOPLh8v
x2uSvZTrN04F01yIA+I1wXpZ4Z47EFKuCngFAKkl9j2fMtE0Q5qNxic89Yq5FLyW9RG+ALDnCG4DpS/ZcES/aRpWu+AzsBskntJoVeHpKhC5kp4R
ekEgg0PKMaN4QdCrfJeKM3zIugSpR7SaijQgc3Sx/E4IMHTD4RHxhCznuAUl0tZY4F6OyDmjN5ntUWUMmLsSZD+ZMdz4VzhgYU2WnD7ck1hyA/ti
TTLgapZJLJMdfRGK1rfxmsSyJzemOmQTjSTinvttRoorrK8VAx1OJxDe6pjPBcj3qp2zMXvfHjvr9p8kbhrIwJnkcvFTOPNaSBa2jY034EfKN4ad
XRp+dfCHrEZLRR0JEl40w7khy44Zb+MfK1TMq0JlwBmeoLmGQzqZWmpdQGdWAjrP33um68cilFWv7l/16mHVq7Mvb+Bs7r48c/XldRimsPrydvbl
7ezLU1cb5p503pUGGpmSgwAI0IYzYhlqTVfFY2BDUAfyb3zsNpc9Dmvs0CrrhL05BXIerD41uwzRaJe181en396ZtGMb8eQUtTQZwQMM67s0D0dr
g7SRGBJYyeNdyMntJoXnlJBV/Jmk+NMtCzme2ZkfLS4Pr/1PpeyrUA786B1yCdcUY5mOExtnmXF+MZkNE9JDNU7JBvrZwEx74F7OLvtBoUWsLuEQ
s41baQjXuEuOVSWzalnoK3xo4P/l+nkt/YFb3pJyNsrc8B63sQscrf3MPLQ0Qxh4YJh3OWlQ6gAlNKX/ykDAnt8MhBFizvKDMYxupBzSliVb4q+p
d7+PLbqg0nWw6mvTU0wvbCoxrB+5DxlwJ/M6zde8zs8Bd+n3gerOseTkscelX3tc4les5bkubDXYKMbhVxSKSywsIxOqyiSBccWKn07Pfji9PyxS
669FtlC3X7Op+bVpTVId3qgTvN5uWlJYvo2V7CjHCQ1nxFdLxhqu8w8Y3n+FAX4dETN+johhzfRkEdorva+e6f2w0vvuyu/zEBzHsMS7M9uGPfc1
PshmzoSVggJ8LywJZIxblezGCQyQcGPA6Q8GnN8luuO1zWYF9H9OEk5fk4SNBdqt57jyrNwvAjvbi9WlQHbg4LhLkcfRyDDPU796B5kH+dvewcKx
3azo3TTwu+JAnkIKLTSzV5wT+xhlZOAENuA2W24EgVIftbWaDJR5C98oOd8oOd4o2egKCdmY/LqmN7kpZMQzXMHALRcWZRj3eqoCvfcjlomnUbgy
G/fNwLqBRoewc94o/bwIM+dFrwBBXz2VpFccp8DdLytiMJtMj0+tj7B5yWvA68/exwY+AWYyilFMhrPMLa+aBtzlGmt+d9T+Yi/i0158bijLf7Gh
TApWw18WrMKasHwSEnIGNUGJ52Ao6PTg5RweLBr2a8vkdSRr9/nKwYDgvbwvB+n+4n0fSCi8kVDq7o2ELh/PGB4dzMouAYvOkcXHO2Y0EtuFAfEK
7GM/wmKh7NGGde4sHJyrr08GWjWpzpDjbHNNLZSBTHp4ydSyCD9bD4DDOAY+79oanpZtBf66gv0SrYERgndle4cCs1rBfkgIgCMHG2agnIELhkUB
cm9aScA3sq29c5ieOaWpTavMqCKX44LE38tx/VoG6YvEfdd/gqRAfrO1ranM/h8plfr30C3LoNnyn8N7LkB/ryVR3OeWa+VYU1jK7Vrohoc/geq5
7vFa6MZq99Tn2Sd7+yklk+ZFdTCJRp8KI2rNe7bxa0CX52cPrMNuTBq7NbNcycxy+5xZ/iOkWl8hVUlh/e70mpBCpuGY63yQwp5wnPlVnPJsqJir
W9HCS/bS4bx05z5S9ggwqyq96mH1qtdrPY4UBMa8JslFc6bVC6hWL2Bijb9Rj/77KHs/OLgAPnixRiCPN2l8Vmm8pvWv/QuGyRBft8Ay6z8utFr+
PnYh8SBBBtcqsyrbi8Qz/EvQGB9L0n5bGHVtRHkOHO2vFpUK+dLaGi7eZYtKCOvl6sa54StqCZcM5gV1nINioO3cOG+hDthOWBMwzb7GGL4nGW9/
Ncm4ugxWtq0r/JshIjJGhP1dhiVxkVP52G5PnLsGzfxWcBFeBRf9t4KL11F0idXLUVTp1hHfGT+KAPdXEWB9FgE6KQK8qj5abdNyYB68Ka+Vhx/v
0N3P9ORrv12IH7sUOeNEfey3k5nkjjNhIJDu0e8O6n1msi9fuXG8dFc8boBT3AN491kS+1M32WeOAyiUvFzWBr+7yHsV58h/16+Amu/qHKi3vjuR
4chlMzegYqGflA1xzLFyFqSvVlql/iaOKq477vz4Upuh1i6fKlMq36Ny06rN6Cv0pwHBuUK4eFjHnE2GNTfc5Nu6GYyZwgkUUwB0Gj67edWDyUte
1Ied3FzjdteDOTHHkRFhZme4tYPd703gejSNPUtwYzziig8zIzm4MZwyUSuEJp8w//B6YA+wKmsJyI95lDlvaiUI7kWlZXQ7rkWlY/Ukfw7G3iNZ
CumS9Cwodb7GPZFvyrgn9TXuif/i1cm5V5FV45vhjeoMkmjY4w0dO7VNnEZn2hqdbVmHCQHSbRtbsVO/h56xrovLU/ImO1lZ9xmk7rMzgTLpQSQU
AlTQ1laggTtk4Y1sBaJDvtYCcXRgcSucHNeo53trVfnuDZcE0mtrFUfp0L0JT2eTVCwRLqmvPJUUhEhCzEtKjQUh8C7WBdmVdO3g7ACywIBrJvHk
EkguJpMAQPqeSfwzHWrD6dujQBlmLYZ7Ct0OxEQy/V4oL4PlJ/kI4PG4HBy9hBI0M+YHq5utvzzK1Qy5xlR+zIN0QaoY2H8v++tnP6YAogqpfo6F
9kdojNI1kNnH2CbJQb3GNiXZh9DsKhXgmk64xe3ebQzLLjgpAj1wpBlxEiA+wyZWNqcC9hh9wnPAfQyG06SUDIiZ1e/6tfj6ARNIG87EVe/RSv2S
jGKEYQQnPt/llJl5OdUBmMZ7K8yogCmH7Vy1ofTGCoojvpfCvNbRpMc6mv2xjga6RjfT9eHVdi2MtffKjLFWZnCDdGEr7mQ7zVwT2OHDTnZOaK/s
ZgFlo2UjBoHv1sIOctKGiXuo0BLJtcssdngYmP/sT3ArOD3X3fJvplmuRx7KwpHyTThbMxiQcy8Nt7uyTKANhjg5+4s7rnGZ02vQlnAy9vnuIeuy
XAZQ7+UuWMsGyyGtOBDWzg0Lfx6Plz7G46W13PQZ6n4kl1gyroLUBAJiisxyRRN0kOWwMoU/2ipNyqzQ1nPu0IZjDS8EAbz6+a/qvW0DV4A1vKp4
mXPCk/hhardslj04xaEmLRNKSJ5gl3cv/XbpTgLKWtvBtbbntdaWe3fYwLi/9u7s8CP3NvQpyX42672S/e95dwyastkQXnHhc44uitNVHzbLLQ14
3k1GZ+MqLBg0rGD0MXOcizYGRhAsXlzzrAeHVLFOS0LeVftWueY3QZTbFUpmQnWofoeSIdsS6B6G5cbMNAd4VjYo1AQRkDVXQG6bDMpUVHA9Wffv
vmjFKuvblg1g6xIduZ4ARJmzFtwKHfY1gXCUCQo4ARPSDmcOtJVYjm7XTGJYqFUcQRqZr+XIHScWIPf5X3aVMBYISZEkMWtTZudKqSlzP7VUeq8K
7Nc0k/GnaSYSjsAzQPBYz8xgrtCcP078Wo1v8d34lqxM+JgOxhdCDblUkjwNnM1pp5O9UAyTmQpHnqUcYi7jHwPX0CZbhFE/JpbcXol9MtZbWCGW
u7BmE26V3Dltd6PlLLdPZBXd2pQ3DyAlGFm4xIiztRueYWPZgRVd5ZYhALti1WIrWSZr1eM9WauCCxpY/Fo5+Eog6upkG48hgr1vFbgMxomLWLmL
I47tLODWzKQd8OgwpwmwzqxuShYfTsetvrhMlhIGUqDNUVmheFIBtsMXcS5cJ/8+nXUc0CllEn3eowjyFU0z32395hmf/D0euIZeS10cbj7944oT
A7vBKKrH8WbFsSb+vHrsz7VK9PUKXurZg0QsH/UrIBXQZRZvb/A0Myr8SQkdlGUMgQOh8zU9wK7JMs2s4QFy5OxSls6Fa9aE/+c1v5yIIGtPunSu
rpVAGdT+hMI+O+Te5U2PTCc3UlUPIe2vjQNM6QzWeLGn4zWE5zmAQcJqNhicUiiW6TjLnErmLg8RJKBjkILLYnABF56+vSdWXQMrfpuWsXrTDA70
sz56h2/j9uDMJp4dyi/jK9XhHbQqpsrNbL+OyAG+UxKv+C59kj1J42Npwmltg6GyYzYO7pSkvQEGwPXt27btueMGgVPwTWVlReH3DDxyZXMqCZXn
Eqx7YjlnLBrOgsizDQWbCkkyiW1NcEWGzZ/nCZrD9j7O3FjRYBwQyw6501gRyB9ghC7vgHDVzOp45EB4GQcmq9ZaBak0tjOrNEhYMrFVgnsCnFGm
HDZ97yEp1x4SFv3fe0gOWXA+rkER0ngVNTPInkMNNazhDL4yqhSK5ySeXxqy8s8BAc+GrGsbdGXhr1/boJnJP+0aIcGcxj1a062Ktt8G/W1f64g4
yq6KLrMhba025U2M/Tm8apc0HMSamzQ48OhFkUHb2ppE+gFpWav2NYnUM9ckzouVD3evq+FymGXFcFQiX9wioN0Q6RodXtgJeaqqCZaOV5raq6rx
wRjGhSdwwDm0z7L32ZhkDDe5QTUAoVou5yk4PcMOcGbcPdat9i5jXg7GlAxnNK1adp7J3LjQ7ZUmCKv2Q3N7eYCnAUErnCKeWK0H+nIeB0DnkDbb
/jfrZT3Frz9bJaXd6avgO8FoTpiylCXuVHEnVlrCuLq7mshRJPujFT8MyQCvVnyVDvdjaGZi3CNzaKYfK2vpIPfn5n313NPIgtgOqsDk1Im/AYQv
B3QY3oVW3T2XQIzMely/czDVzt1Hs4OhpcIBa8wrtDH2EdeSGECm0faQwB0g2p292mDp4Koxnxms3XCdkKcWOBnr3k53ADxkY/cp+gaMYuPBTVQx
UOfaeIUXWQoTvCRyV2KA84fxPiW9enBiD/7uweG8jNWDI97zx/7X9K4Jf+x/VXxA4kOIFuz8cMTvkNkOUYYr8cMfjCZC7LI7P/dhz++d4vbahz2Z
vGcwAJfIoo+16NAxGKG5ajofmlPt4UZ12UHkTnWcgOde2lzCkNytXrX6nBHnXjPi1iSjqkAmyL7vPXeuMGyJu+GARU5LnvILBzLsK6zN5CRezTgI
Im4/TO2OH8W9aV/FvUaKe38Pk2Z5Uwag/7p/fsUdyhV3CF8z6Z7bsq8ARRe2+wkFP9ZqB+g6PDS5n/BdQeMhQ9T/oaqtMgLOjOZr19LdmQtDadQb
srzX0Y9O3gf1z4qTGWvjYCZIP0gjVIXWZoLlslW9yGSyHUdAitoZa4ih4aXJkWD5pReSrRqGZACaTRi3FuqmTZpPNG2tCcAn/S4iZ+yZBaK2JclE
QMYGkbS+QkCPmp+5an4uBP/3CcW7c/O1qLtYKPla1B3yKjtNLKNkaUNfjQIA0e9yHxjTFlXeBnf2sJGVM+vhyM5sAVizzYl97K0yXYjHylXW0eEc
cSngXmFeKxb7zAQNZboTPx4j0MNvayrrbA5s4XS5hC7GywZYblscCxbwHQWg2ATDyp6tHL20yv7EwFnHj1ihk1jhB+PkH0D3CtWdexpnMqDeB+Ep
YIBU+p+49XBa2qr4JwT1MT6XeQUWB1IGfhkZVl/FKN91EIwg3ZXYVeogILxhK+MEgC21NKhZABO/ZvA6aM5rBm/6pxm81qv83RvcpRY5emb7wWT9
ebJJ7BSvrgmeJPQD/eocpQHgpmI4OWt0k+mAUp3P/icnldrw2kAJc6yN4H/cvjfL6tj9Km+5Qhcsg7wmNXJLAICy6WdvZ4t1V7PGk72p7IrnsJTZ
ZFlwbce7PG/vnOBGRPDqNjnYbQJuJ+Pyej/DGgaxKV6WPkAx4ZsAZ6LlYK//+o/jaFJ9kZTjIqdNyimJKbo/7umlaU0vnY/ppQxpAiY4BRuijyGm
jI6s9kdJhP/sILyWPzrZFqlZGaE3jnUpHCjA+kG2uMgw9aMchppD+cEnhe0tHoo/YxYeOFf/8Pd4K1mdCeT8URjIqerlr6aqV36Z5djKXVz5LEAm
kBZznEYCSWvcdS3PPGet5hxebU6WWX2Zte1h1tpt1qDiuNevsu7fljn3VYLR7xKMK1i0X8GiyWBRXsEitdhyfXYSsvYkQgU55m8y8Juv4pOPwur4
WVjNvtpOtvLsq+2rr/aAPEFhuSYIwnW++moV9ycY2MFUGeq83NLssIB4OTiTQFQSFFhGCWv0epD9UZ3z3eYB1jFmNYyyeRBOLseCO4cvFYvwue59
t2v4yVd3FSPvrLd63SXYp43hb1q2H0m0tfD8MYL2Yr8qcOfrKp7hfnqx75TicE5IWoT7TSdMJFQeTKcYqTY1rLoHHWhAhgT32QBOhwuGhsLV9rkm
uOqTpTaKu+sYgYdBPxMOsgbWiYQRX7GANWJjXJ0oLF/en86cE4YZEJC1lJwtGz8XyYb9WmkKCYVrDpzDDBhsJ+S4Mbti4AknC9DrWnzwc7SbKG6U
PsQVOw0/pgL/e1mv9LEqzjO+h5XE/auNFSgX0jMzp1854G3G7fsByLp63g6Z3UNjdcrIEMNaOzb0deA8te92Xp34a1t2iL9ty24q3Pt1+J0JYAan
zXP8w+wW9mCGqwdzx129ezBbBebyOS4oCvoBSxTtOc94cj8YT23K3khSnMDq9zuBk5jAITn9TOAoaOo4PzYJfawuXxNHZMEAXkwPaxmPYwyCy9jL
aEGfe+YMIduHDj5+DGGLP4aw/Wlyx3OHE2drNnYjNmDtZCcMFTB22jgqinFhWjbIFjB+Bm6h2bQR9EJcQeDuUUnkXPvnHh3X/tlxLYu9r47rvfyw
h/OzJO0M4+/3Y82iuodtlxWI/2jlyu9WLp8n5/t5iBRrPMdVE/zHke2wYjCI98qb75HtX8suznTW43+6STVyy5zaaUajww9u/FwXyhaimaBEQcaP
ctlDGjV1wAvQ+sCB6dA+7x91HmshSv+HhSh9LrPwPS3KyDuyrowN6b03UHHuMOcImcgETlwJnKSPevXZ7vRTFKi8Kl7Ycyt9Eh9hXZaX4lWlMmBl
Pw6WnCiO/FyuwKwpdMzQrCl0f4BZVHJqAqBdLboAu3POWO0apNziD5wAhqc0b/G85wG4t3R+pH+ldGuAKb1KtwgaWVn1Lt0Crmad1bHSADJfsP+q
fzpe+RfIyXyXdcFG7lxisfZg3jknljt97Fi6Vli8g10KpkW5Rz0IeK8+GXhJXicYCQBje/ZTGjcJf2E15BL/rrqJrWBfpcj7sxT5ngb1511vu1N2
Jc5BJaaMqAB2pNFl4lydMhKm018xIskmq5GVkXFoUaszAzJoKXTk60mF+9rLG1m3Aw9Ao25Owq2Cb03hLkW98/r/ZHZO/PI55D58uLN2u7M1MOWz
p5oFMT/LHMJyPhOHzaHHuubHbjccl+BQz/HhCsgg1tWJD5PMfeR3I1cCjZsrmMdTGAzSenaVQPjBB9LD9ANXQE7swE9C2id3i51B4q6Mm0P5HEHH
jOEq1UyvUT1Z9oxIJGTZMWoXN+Xds8VeUyfU5axN3yyQLjPEftviiQ/pNhu3rW/SSJFh24x8VP9BrOFnN8bqFdv11z6zNk5CEdbb0y4T24+xDZD2
UfbpIVgcRHgepm6kZ9zvY7bEFWZnv3uw7hU9fEBZ8JVlTTasWZtpVU6tAjYlJbtMXHUWEoLHsLiEWTDfWboTN1lEFcw5pfRecY8xU5snxNWBLofO
ySuXnQq/lcHLXHsw6zXXflzR5ChkOqXHYPtW7mgyz3JqGjzu0ozP5rONid7X3iKujoLAU+fDqnq1ikKSVhYzPGIg1nK/cSlzymVzbsaU6ImXxR6K
ChovBc3mirD37sRH3ztiOb/pOV61wd/i5Rtzmq1tFob14DQyGVxHMPdz5oKEez+nMz72uBF8B2jFe2AaV+ni8+CgGvPndBRJcMYuY9pd4qjFysEW
Le3c5oBP2I8G52kN6ya0C25NBzQ/ZxGE9nMWwa+jQ/Z7dIiBHFi1RnTNLFlfNUjRWE/fOUsunTMOqxhgvECGMgDTTMJzoIIqzCqEA19JUpSCdWsJ
DIjLBj8mU/KPMUo/Ifys/rZh7CBOaxdsZMIGVz6Y5AJpYuWIhaUda+gpnhHQA3c6JKn3czd7+9cuWFgE3Txn7HlW4tQqlThdANz+AnBjNepDT/+l
Ub+zODRzbkVacyvUmluBKwrZ9vdgtXgNVnvsFq9XId1n4yd38sTA5CkDF981A/NaAvZVM2AcN1mOzPFXCdxRF7/toQb8kTm7dxx3lTbHfy1thoDg
XL3myFWxOvBL06jCAvaG09X9hMpKbczpj2PzA69yck6UTDRhxSK4NGcWgMLBLsC6rbKtKR22exzAQGrlu6U4lx1d6RlEc2teuYQ93J9mWJg1wwKq
H9a6SyezRMEWkuSolEt6Fy0090qPHu9KKrx9wKcP8bHUA99fWJfBXLHMCwOUgH33EAPIDCfzElLseOEdREevZeP/sMhD4lI7TaOKCxLFxVpfHe5K
Otw5XDutzn/jculssKgAYmeoQlbgPMn+FWMlSsG/qNiYwfjYGjtXbytrv692YA48vNqBZVZ3ZuuDktaHXjV0ZbU+RNasmNX6IH36uzkaMxAJpwET
oDyExWU+CGuAJ2ex5ChZZFkrNim9RQYOBCn/jv7u2JL4k+wRybIi1b+3k4RrO8ldzFffJRCMq+4M3zzLw1nWLFZdFhN52rxxTerz+poVksxkM7q8
4aoDyCbNK5ekwslPD823wAUGaH80GCFZd8Ml0AAXjVFHuNGoLtDwG6FcOZshOXDji2EOfLjh+2C4HNCzHzZqMqtR2Chz58C/9v+O7/2/Zq2agHi/
RzDKPnIc+7gqbhkTGawgAQm9WglK/2Vq8AnheCxRcb3dyZIfPs88ay68eAHaSEn01B/Lh+78zaP8Nd/lr9eaFnevadnnxzjsj0JprSt+nqwCAvo6
h5RKy04/kNkfK2+3trJSEMgqK2/XRJNYTOX8iv3B8vK7mr+T5ZUhi0/5d2R5+aqJZqFRuguN2io0CnBc6lV7y+WpMMf+uEY5vOq+t/VpysenWTGf
u/A78B/EkwQwsGxhceF/8ZJ2+FMqPyVrxm2a7WMgJpfA+PkKrwPzhXxFqhiWk4xhejeLsog2PIpodzotxrgAy/fJoJvijBjwhdpgiK00luMppNMG
9AloI8+T28nwCd4biu9xjc3UfxydL6O1BwxzUeLP4W7thD+HOxJ5A/Fko1tUxdBHbtA6fA0O0MtUUHZ8L+J4cDgMgzKsDSI4h6Gxa8OqK2Fywrav
0pcAZ/UKIj1HuPzrfHonkzh6WnsouuyhkMmG9y7WwFCIDDoLrzYKkPUhbRTRyDIC1q131nGXdLpm4OX1mvkMYw0dM0cXVBBEbOE4GvxOY287I3+g
4qqt3amiacDcYeMHZq3eVJKTFaWiY8yZuR6+MlD4u/QLGD7J0GY40qbDKRDjj3xMLT7WP/hYa9cGN3wxfbYo0wQ3YMSRzqsXEv0Mui6VwDC/2rbE
4mW4yh0Yk5+Eg+m0LfJ53/sT09+lLJfJly6dzmyalgle8QYCwwgQWKF80Px4Zm9fHjiz4/PlgdfKm6qA/RVwZcvvkCLnxvtX7jGt3GP7MSuJJUCf
GbrDwG3osDmNs57TNqBVC3y16/FpOfJtOcb5YTk6l5sty8H7AVaC4Q80/GwoiOyjgeHPQEiKEcnYgXq3HEb9vdBLXaux/ErvwXooz+YZtofB3N7p
PSfpPQgQ/KSWIUC9GjZN1uFKGxmQDs/Ot1gjNjn4JL2wPieKLqzPKYY0RYFYf/a6mt1gQwFLnea/OLZUcmiLe8QqyzW88Q56c/Uynl5+P+erD+bV
Mlm/tkx+jS9Sr/lF7OiQsgjoODcVXA0d3zP+xqu0IaxmZvOv8H0H0Zd80h2na6843TCf3eErfLA8JicpcnH4PeV3JhYQ+HPV8/g1kXmV7N6o1a9O
zVe8ToHoSyn3aLvjwjlZm6YLC/wjuNYNSgWGfG0AuLPT77l+QmbDy7GztKumz10ha6hZAzv6GGpmQcEZ/bqU4jGsOL/Xu526urjaveyr3UsKR9cu
kSl9Cyyk52ZAQbyD4FatsVZgLf4aa3VtC4jbdm8LUPe2gLa2BVxtW2NeTSxzzTnc1seaPe2mf6DHHLZxbiAajvUdbgMbNRMuFqZ+4z/Zk6IT4Aka
W77XvJk/jG40L9b+oqJUw3B0UtEO2EovJFT0fFHR8aqPecKm9hM21avG9ln8B9lZwcOrofoaJ38FQh29Rn4wimvZ/KPYrP5ebNYfxWa4MAjQBjYn
JXnixqxmIAhPlZmlzlGPzb9BCXRhNepwqZtii3laeTEOieIYE0bcN6j+93Ci+TEochiDuyucV5ygA9aGjZECiHWbEPqdzIEtnfgkXKG66pzXHAb1
nsOQ9FNyvpaG4vVlaWi+ol7jQneuc+Qb4x8ny9lJB7zicm3OBMoANWJwngss42uBpVn1LHDc0nDWR7fCFiCeYXFE0eE0uJqONbpu1ZAkqs9Vq6g2
payEOdW/DF5RVx5SNo8VAGfGry+Ac7Wy0fLRv5dxvjZ3cPXxr5Mw7pTbXCm3dKOlNe6JWyHNMNrJ6IeGu1nTnqSAe8epaXMXcOM0NeThUcCNN85w
lzE1jnqOHMhkM/iD0muH2ecQibsHLHwuqVgEMwDxln5Pew1XpnEo8FJW9hmOOZDSpML5RYaUmxspjSk4OMs8g905wbyDfx7dGHbCSAs8CyiZVc6A
GI9K0p+Z3tUJJ3Mcv2b9XuNE5i+d1SA2XdZ7p8bzn6txe0rj9ng0br+n0d+Jq2savYyjj5yV/NiRYeJPlP3ZHsvQrPEOhk2Tn+K2XstUoilWWjjV
WMtUGszGtUxFEgcrABlXGb3Ij8Ghd/ZTclAwE3s7o08qn3CQD3zQ58rL3BFn0GUonTTbzke3aVbvZlu5s+MaHB65De1W1UaYdK+Eee73/VxiVf9t
idU+wN2BmhhOYbqBiXHSl5P7y4UHNvBobqTmZkx2xxwC/j43Uo9rI3X1BwuXV6WR1fC0rKTtY1v9ES5Ig3c7bRuH5GDyAXRQ7mF3Iz+G3W3KbRx0
4v1euRl5VR/CenMj1uyvRZirJu5ehPlRE7dDWCwMZQYoyBymDU+H480c0hPht6OWfK6AY1tkvyJYqSv4FgWhh/IBEW/rWybY6PUtcwMIgiqYNUKL
dlwKPMg0X3acQ3F3XK7Ma7v67uEPcGppsKMOVqhzfbmXXa0m44qLrYRPdbvopCv1kA6tMMs1dOTfdm/1p7ubj96pq9dsZVOBU+GUOH0CZKjokxvJ
/v/KrgVndpNZbuluARlsIwziJZD3v5Fb1eCx5/El+XMiRTn6kjNjQ3d1d3XVSRozYy/+trKhiPLWr0hYdHQBoGucNa4Aw0Mw4NDI/ZzpAu2HJuDL
Jhs3BLJYUYNQYT70ICsNKfbEcWeQz8fFGTcWZ+rH4swhy3Y+VpdXjQvened+Ay4CngONQXPH67Xid8ZdNWA9vfDIXMucDmX5wHr4sFXMoorKPMyh
OPZZudFZ187WJmIxfh+p+5CVNh+jeC7RclZAdsWhqxQy25MGCN9Ha2KfN7gnyqI9PfQG7nIy1ZYr2TOZnmyfiJu0p/SMNMxQyRlEDRNqNu2jYZYJ
8WfDbNYe/h9qDzwre3MeCv6lfnDAAM5GP7XaP45DqEjWlHVjzCQWKxVvqlWcVoPXiYIRd4BuvLszUxyN+ZJsb+5dMle6+M3/uZSClKil/JZOnCyZ
AzHnViqfrPQeJHcJp4a9FC2dLycmSozy9aWwuq9RFFa3c+ipOP3DW8pPz8ax+yHDo0uGfWwHtGnYsX459ry76xJOtfW0QLtcW9ysamRwKg6Tx3Q0
AxxS6F9kJLMBLgA05AUOGZgD8e65blWQAhGRWH6lHUfaAOOjRswBd13yhT51p4gmSYSqnlsCLq69xBgAPwM1Z3AT2T+THo4lw7FzyEz166eZwSwl
nkVhZYtZ2p5Lt0tHla2oToqnupP7z0xfVa0yVKBsYLn0JYVmHSzZq9JkD04KCkoA4mk5VVcWaAeFjB2+GYkOCYBZYGIjih2Xlx6zgb42eBTbstPa
US4vEkrRo4Yyvy2y1WYiwgVuwQBSCLe0e905VbUxsUSyY/DncOlwOLrDldMAQjiL8XJlPzOqco8bGpkGX23qeWHu+Pm2q/vW6rx2Kt9bnepudbr/
ZAu/bbSFb3iCsn8BoGIB0hyOZF0oCU1WBNIwDQ0BBLX1FFUIfzkLJFoLCE3tm433LIZe307jinh8wvCzSlR3lTjFjXil9bjS9lL8cY8rfWuaRXfz
Sh+aZlOhZqNl3aSn4k1FapMZEr+4Yzts2yM1Hc2eZU+Yd+t/0QtQY/UetSCv05VDp1FfuY36xCBm8HLL7vWQr5UqYtolHSqgpjrCh1lSHvKLpFFy
5RdYgiIMlImiR6UZgisrMB215eeg/5BXM0TlW7jNkUOX/81u7ST7HVy6fEkctU2TcaiIGnjz+IGNYQdTVutxuFYko41YuJE82gM3w67lehdiD9tn
qW5LbfaDmW+03q+/tvZSh9reFcTqUBDDAxPxvtkBzbQLmh3Qwa9ZEc1cOIYjbl6FQNDUYJj1lXa7qe4lGZwYpBFvRSk3MA+m1J5R0oil59q7oxa4
i3RUQRm1oDbqSAdhjT5e8zPZ457U3FKogMMS9NwCq7Ri6ga4UBROHRKKr5zR2kXpN9Odj6VS/AEGJzohng5JCLWjAE0LsDV/eEpCmLA/NSGQSIdC
dH2ZaZ+q12BRMJeG+o3KJEExYohOtNU1431VZAAWIACKZEWxMKi3PlX7KcoooxrkDJfLkK8p2ZdCCssxCHmTwjKK+UKhCh6Ce8JKE78zHkAnozn5
H3cEkGCXCIRbfTo14wpXEpCikEY8bcvYG9M14qu0nbbgk2WLt7/iEvcGMI9qFjFtX3CqZR00Mcog/wzmu8+AvMzJloQY3PMTaDiitopIU5z74GXg
FPCbokLOIk7haQRO5+PR30zqfEKT6Ra/C43uPwrt8gjUOt/ngpcX+oL/MrSObyim6AvgysE9UkESKDh2BDL8g0xjivmkQAF7FMa4vgHFtUZppvAI
9CaCZtquUx1CWC97i+ShzpbktOa8LRGlDXJQP2g7DNO4RxQ+KvPOxYRpVo/pT2icITDw5876GsfKNfZ4Mo3CHNkPlv5Gic53PGZ4l3SxzyIvLtRG
ytdbKt8gc64I09L7Mbv0fi5pG1Oa4rTn4PoljwjgkJJ9lmyHONjmkS7xoYF16BCHgh0HynD9iLMQZSi/j8Sn1yMl+6m7mv9Bd9UHLrvqlc5rDsCV
++81koKVT5nAFOT+o9Entcplft+DD0/fVWrwz5r8aLhLlXMmNVhgTwGsFAx9NWIfjiqUvmwS4Y06VVxVFIkgFNQR+BHnEGmkJ66yCnyiBCcen0aB
QUY0iiDEaL0zCqud456K3C6RpCaJJIDIbUXe+m7vHK/2zrBztuk0GyqWuYYTZVNNPcbbrXyNaVnSn0Auv9BLmly/dZifbchJw+r1mDr8q8icVUB7
79mpzEb69Bu3GOwZFh+4G3UEgOcFoW05X84m6g8ZviLsXbU9ucKCN2ReSdWke7+34SHawjxrloWDvi3vZ1k292yztGebRV2v9NlmYVTMp+xPG7Wc
4VzIictcFaOPdMmWSzprFrbdm0xsfW626TfhEvfT1WXOUsrwLHGyBPV7llI53H0S+v9aR/HKcBXvuP041Z9+nGn4cb5Ij/Zdqq9OqT5FBuct1Uea
wPFTeJa6szf9Rk36jRhvDFBzVNc/WyN/T3GCNB1xoYZ9iRL7Et4tWusixuGAI6vp3NII9SaH+mu558vZ2BfOBXPZFN4qwAVNXukvgLyIh9QRLbYk
e0ZZTzVZDrkAqiId9qbz6+ZrGv2cy0jgfc+RBMsbTMlpoB7oiqtMlXSykXvgQhxgko/DAt252CKKkAW5gj5AKfu5UxW13wzpHyiXUGBfzq31dm7F
9zG2PJQncRjJgDqm+jNNWqZ5QqX4OFvp7OADgLjkzViO5bR2m+pI5AG9+ETHnAjNmlU90RjAHgJ8ZKG0/+LV2d+8ulzYNe/esPVQUOBQsouGg/vy
WvRscve/CTvpqWo85QoooOOlpyS0HFPEyqlEY3xwJ87OtHJqw8qJJwvgglrGOFDu31zl8GfibOFovfl4Sq+x4Ba2917js+MfpOMfucPCx5GGJMwQ
4W1BeP1snQgZW6RYh0W6/ZLrK0Ouz+imd2SAoeFV22lQkVlvgcSpNkAzcoCkYL23jUISgx9FFS28owl5psE4fl6j9jy5bLh0BLNMwldh/l9SQDbP
y4BLK3AdOapTz2fDiTWUFKD3jmtALifd8/DjdtoYWyrvH8dlq3ZVmcPuPYgERnwIXr0mK6l9LjPdGuPmQ2N8fWqMr5bfD1+ID4Gkj4evNY7ql6/1
tSv2wddvxydh/80vS1r30W+53mbg7mFfW1/2tf9246qZNjQfpgBmmAKYYQqg/sm7I21yB18yXKPIoqMuv8eIuS6WqEnQlXLZdcpI36iP1oJu6GTh
CJqJ+lDec8jT2H/j6KJ01U7U4Hg/gGNrdr6Wi5LwZhr+/XS/aIXc28wXrTDOoc+2Kk44y63W277Uej3qrT9YKO0XC+U6N/H73JRn14ENuWJw2L4b
iflnI3FqDSGkoQZXUhay2ScVeE3nijhVqQJyXAZFPAXigPY6BRJv/+99qW8sGeEkIdSTVYH3uiBckTQ5fNPOcrZiTmThiLcx1Jh9LH3nNuEBiOv2
uqtSd/4KFqWRWgxn9vwcsfht3cfymkjX95BPHPwiLr305hOFEFqyDoUQ+T5IrmItN0/Px+LA+q+LA1oxLaXYj7huc07wpJU00krstI68+iYUro91
9E0CLt/wE3sn0QzC/CeJBtX5ugLDVs6hClABPa1RYpexHW1/bkcHQlaWGIFdRvr/rXGhjrjSymVgSJKflx6Bq9nRx8G2VgMeTBF+k1HXRodyJe75
PGnFyQfuVpw6Sqf1AlC/Ba5BOZ0QHg+zUTUSleJJ2asdIXM5z0Hc6uequmUrCOUUSp4myjiH2ZsRr4dkxtyW1DxLSCMkhSbqNwo3S3HrSnGCS2qe
3qWa/H9ANyCn5tsAAA==
"""

_raw = gzip.decompress(base64.b64decode("".join(_BENCHMARK_B64.split())))
_md5 = hashlib.md5(_raw).hexdigest()
assert _md5 == PUBLISHED_MD5, f"embedded benchmark is corrupted: {_md5}"

with open("amp_dataset.csv", "wb") as _f:
    _f.write(_raw)
data = pd.read_csv(io.BytesIO(_raw))

print(f"Published benchmark loaded from the notebook itself: {len(data)} peptides "
      f"({int(data.label.sum())} AMP / {int((1 - data.label).sum())} non-AMP)")
print(f"checksum {_md5} verified - every number below reproduces the paper")
print("amp_dataset.csv written for the cells that follow; nothing was downloaded.")
print("Set REBUILD_FROM_UNIPROT = True to rebuild from the live API instead,")
print("but note that Swiss-Prot keeps growing, so a rebuild will not match the paper.")

import pandas as pd

PUBLISHED_N, PUBLISHED_MD5 = 1724, "0c1ce4da5e0b8282b883436ec33fb8c6"
if REBUILD_FROM_UNIPROT:
    pos = fetch_uniprot(
        "reviewed:true AND keyword:KW-0929 AND length:[10 TO 50] NOT fragment:true",
        max_records=3000)
    pos["label"] = 1

    neg = fetch_uniprot(
        "reviewed:true AND length:[10 TO 50] NOT keyword:KW-0929 NOT fragment:true",
        max_records=3000)
    neg["label"] = 0

    print("raw positives:", len(pos), "| raw negatives:", len(neg))
    print("columns:", pos.columns.tolist())


    STANDARD = set("ACDEFGHIKLMNPQRSTVWY")

    def clean(df):
        df = df.copy()
        df["sequence"] = df["sequence"].str.upper().str.strip()
        df = df[df["sequence"].apply(lambda s: set(s) <= STANDARD)]
        df = df[df["sequence"].str.len().between(10, 50)]
        df = df.drop_duplicates(subset="sequence")
        return df[["sequence", "label"]]

    pos_c, neg_c = clean(pos), clean(neg)

    overlap = set(pos_c.sequence) & set(neg_c.sequence)
    pos_c = pos_c[~pos_c.sequence.isin(overlap)]
    neg_c = neg_c[~neg_c.sequence.isin(overlap)]

    n = min(len(pos_c), len(neg_c))
    data = (pd.concat([pos_c.sample(n, random_state=42),
                       neg_c.sample(n, random_state=42)])
              .sample(frac=1, random_state=42)
              .reset_index(drop=True))

    data.to_csv("amp_dataset.csv", index=False)
    print("cleaned & balanced:", data.shape)
    print(data.label.value_counts().to_dict())
    data.head()



import matplotlib.pyplot as plt
data["len"] = data.sequence.str.len()
print(data.groupby("label")["len"].describe()[["mean", "min", "max"]])
data["len"].hist(by=data["label"], bins=20, figsize=(9, 3))
plt.tight_layout(); plt.show()


import math, numpy as np, pandas as pd

AA = "ACDEFGHIKLMNPQRSTVWY"
KD  = {"A":1.8,"R":-4.5,"N":-3.5,"D":-3.5,"C":2.5,"Q":-3.5,"E":-3.5,"G":-0.4,
       "H":-3.2,"I":4.5,"L":3.8,"K":-3.9,"M":1.9,"F":2.8,"P":-1.6,"S":-0.8,
       "T":-0.7,"W":-0.9,"Y":-1.3,"V":4.2}
EIS = {"A":0.62,"R":-2.53,"N":-0.78,"D":-0.90,"C":0.29,"Q":-0.85,"E":-0.74,
       "G":0.48,"H":-0.40,"I":1.38,"L":1.06,"K":-1.50,"M":0.64,"F":1.19,
       "P":0.12,"S":-0.18,"T":-0.05,"W":0.81,"Y":0.26,"V":1.08}
PKA = {"D":3.65,"E":4.25,"C":8.33,"Y":10.07,"H":6.00,"K":10.53,"R":12.48}

def net_charge(seq, pH=7.0):
    pos = 1/(1+10**(pH-8.6)); neg = 1/(1+10**(3.6-pH))
    for a in seq:
        if a in "KRH":   pos += 1/(1+10**(pH-PKA[a]))
        elif a in "DECY": neg += 1/(1+10**(PKA[a]-pH))
    return pos - neg

def gravy(seq):       return sum(KD[a] for a in seq)/len(seq)
def aromaticity(seq): return sum(a in "FWY" for a in seq)/len(seq)
def frac_pos(seq):    return sum(a in "KR"  for a in seq)/len(seq)

def hydrophobic_moment(seq, angle=100):
    rad = math.radians(angle)
    s = sum(EIS[a]*math.sin(i*rad) for i,a in enumerate(seq))
    c = sum(EIS[a]*math.cos(i*rad) for i,a in enumerate(seq))
    return math.sqrt(s*s + c*c)/len(seq)

def aac(seq):  return [seq.count(a)/len(seq) for a in AA]


def featurize(seq):
    seq = str(seq).upper()
    return aac(seq) + [len(seq), net_charge(seq), gravy(seq),
                       hydrophobic_moment(seq), aromaticity(seq), frac_pos(seq)]

NAMES = [f"AAC_{a}" for a in AA] + ["length","net_charge","gravy",
         "hydrophobic_moment","aromaticity","frac_positive"]

df = pd.read_csv("amp_dataset.csv")
X = np.array([featurize(s) for s in df.sequence])
y = df.label.values
print("X:", X.shape, "| y:", y.shape)

feat = pd.DataFrame(X, columns=NAMES)
feat.head()


import matplotlib.pyplot as plt
chk = feat.copy(); chk["label"] = y
print(chk.groupby("label")[["net_charge","hydrophobic_moment","gravy","frac_positive"]].mean().round(3))

fig, axes = plt.subplots(1, 3, figsize=(12, 3.5))
for ax, col in zip(axes, ["net_charge","hydrophobic_moment","gravy"]):
    chk.boxplot(column=col, by="label", ax=ax); ax.set_title(col); ax.set_xlabel("label (0=non-AMP, 1=AMP)")
plt.suptitle(""); plt.tight_layout(); plt.show()


import warnings; warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.svm import SVC

models = {
    "Logistic Reg.":  LogisticRegression(max_iter=2000),
    "Random Forest":  RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=0),
    "Grad. Boosting": HistGradientBoostingClassifier(max_iter=300, learning_rate=0.08, random_state=0),
    "SVM (RBF)":      SVC(probability=True, random_state=0),
}

cv = StratifiedKFold(5, shuffle=True, random_state=1)
print("5-fold CV ROC-AUC:")
scores = {}
for name, m in models.items():
    pipe = Pipeline([("scale", StandardScaler()), ("clf", m)])
    sc = cross_val_score(pipe, X, y, cv=cv, scoring="roc_auc", n_jobs=-1)
    scores[name] = sc.mean()
    print(f"  {name:16s} {sc.mean():.3f} ± {sc.std():.3f}")

best_name = max(scores, key=scores.get)
print("\nBest model:", best_name)


import numpy as np, matplotlib.pyplot as plt
from sklearn.metrics import (roc_auc_score, roc_curve, accuracy_score, f1_score,
                             precision_score, recall_score, confusion_matrix)

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.25, stratify=y, random_state=3)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

for name, m in models.items():
    p = Pipeline([("s", StandardScaler()), ("c", m)]).fit(Xtr, ytr)
    pr = p.predict_proba(Xte)[:, 1]
    fpr, tpr, _ = roc_curve(yte, pr)
    ax1.plot(fpr, tpr, lw=2, label=f"{name} (AUC={roc_auc_score(yte, pr):.3f})")
ax1.plot([0, 1], [0, 1], "k--", alpha=.5)
ax1.set_xlabel("False positive rate"); ax1.set_ylabel("True positive rate")
ax1.set_title("ROC curves"); ax1.legend(loc="lower right"); ax1.grid(alpha=.3)

best = Pipeline([("s", StandardScaler()), ("c", models[best_name])]).fit(Xtr, ytr)
pr = best.predict_proba(Xte)[:, 1]; pred = (pr > 0.5).astype(int)
print(f"{best_name} — held-out test:")
print(f"  AUC={roc_auc_score(yte,pr):.3f}  acc={accuracy_score(yte,pred):.3f}  "
      f"F1={f1_score(yte,pred):.3f}  prec={precision_score(yte,pred):.3f}  rec={recall_score(yte,pred):.3f}")

cm = confusion_matrix(yte, pred)
im = ax2.imshow(cm, cmap="Blues")
for (i, j), v in np.ndenumerate(cm):
    ax2.text(j, i, str(v), ha="center", va="center",
             color="white" if v > cm.max()/2 else "black", fontsize=15)
ax2.set_xticks([0,1]); ax2.set_yticks([0,1])
ax2.set_xticklabels(["non-AMP","AMP"]); ax2.set_yticklabels(["non-AMP","AMP"])
ax2.set_xlabel("Predicted"); ax2.set_ylabel("True"); ax2.set_title(f"Confusion — {best_name}")
plt.tight_layout(); plt.show()


rf = RandomForestClassifier(n_estimators=400, n_jobs=-1, random_state=0)
rf.fit(StandardScaler().fit_transform(X), y)
imp = pd.Series(rf.feature_importances_, index=NAMES).sort_values()[-15:]

plt.figure(figsize=(7, 5))
imp.plot.barh(color="#2a9d8f")
plt.xlabel("Random-forest importance")
plt.title("Top 15 features")
plt.tight_layout(); plt.show()


subprocess.run("pip install -q transformers", shell=True, check=True)
import torch, numpy as np
from transformers import AutoTokenizer, AutoModel

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

MODEL = "facebook/esm2_t30_150M_UR50D"   #   (480-d). : esm2_t30_150M_UR50D
tok   = AutoTokenizer.from_pretrained(MODEL)
esm   = AutoModel.from_pretrained(MODEL).to(device).eval()
print("loaded:", MODEL)


def embed(seqs, batch_size=32, max_len=60):
    out_all = []
    for i in range(0, len(seqs), batch_size):
        batch = [str(s).upper() for s in seqs[i:i+batch_size]]
        enc = tok(batch, return_tensors="pt", padding=True,
                  truncation=True, max_length=max_len)
        enc = {k: v.to(device) for k, v in enc.items()}
        with torch.no_grad():
            h = esm(**enc).last_hidden_state
        mask = enc["attention_mask"].unsqueeze(-1)
        mean = (h * mask).sum(1) / mask.sum(1).clamp(min=1)
        out_all.append(mean.cpu().numpy())
        if (i // batch_size) % 10 == 0:
            print(f"  embedded {i+len(batch)}/{len(seqs)}")
    return np.vstack(out_all)


X_esm = embed(df.sequence.tolist())
print("X_esm:", X_esm.shape)


from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

cv = StratifiedKFold(5, shuffle=True, random_state=1)

def evaluate(features, name):
    for clf, cname in [(LogisticRegression(max_iter=3000), "LogReg"),
                       (RandomForestClassifier(n_estimators=300, n_jobs=-1,
                                               random_state=0), "RandForest")]:
        pipe = Pipeline([("s", StandardScaler()), ("c", clf)])
        auc = cross_val_score(pipe, features, y, cv=cv, scoring="roc_auc", n_jobs=-1)
        print(f"  {name:18s} + {cname:11s}  AUC = {auc.mean():.3f} ± {auc.std():.3f}")

print("Comparison (5-fold CV ROC-AUC):")
evaluate(X,      "Handcrafted (26)")
evaluate(X_esm,  "ESM-2 (480)")
evaluate(np.hstack([X, X_esm]), "Combined")


HB_D = {"A":0,"R":5,"N":2,"D":0,"C":1,"Q":2,"E":0,"G":0,"H":1,"I":0,
        "L":0,"K":3,"M":0,"F":0,"P":0,"S":1,"T":1,"W":1,"Y":1,"V":0}
HB_A = {"A":0,"R":0,"N":1,"D":2,"C":0,"Q":1,"E":2,"G":0,"H":1,"I":0,
        "L":0,"K":0,"M":0,"F":0,"P":0,"S":1,"T":1,"W":0,"Y":1,"V":0}

WW_IF  = {"A":0.17,"R":0.81,"N":0.42,"D":1.23,"C":-0.24,"Q":0.58,"E":2.02,"G":0.01,
          "H":0.17,"I":-0.31,"L":-0.56,"K":0.99,"M":-0.23,"F":-1.13,"P":0.45,
          "S":0.13,"T":0.14,"W":-1.85,"Y":-0.94,"V":0.07}
WW_OCT = {"A":0.50,"R":1.81,"N":0.85,"D":3.64,"C":-0.02,"Q":0.77,"E":3.63,"G":1.15,
          "H":0.11,"I":-1.12,"L":-1.25,"K":2.80,"M":-0.67,"F":-1.71,"P":0.14,
          "S":0.46,"T":0.25,"W":-2.09,"Y":-0.71,"V":-0.46}

VOL = {"A":88.6,"R":173.4,"N":114.1,"D":111.1,"C":108.5,"Q":143.8,"E":138.4,"G":60.1,
       "H":153.2,"I":166.7,"L":166.7,"K":168.6,"M":162.9,"F":189.9,"P":112.7,
       "S":89.0,"T":116.1,"W":227.8,"Y":193.6,"V":140.0}
AROM, CATION, CHARGED = set("FWY"), set("KR"), set("DEKRH")


def featurize_interactions(s):
    s = str(s).upper(); L = len(s)
    hb_d = sum(HB_D[a] for a in s); hb_a = sum(HB_A[a] for a in s)
    wif  = sum(WW_IF[a]  for a in s)/L
    woct = sum(WW_OCT[a] for a in s)/L
    vol  = sum(VOL[a]    for a in s)/L
    charged = sum(a in CHARGED for a in s)/L
    arom    = sum(a in AROM   for a in s)/L
    fpos    = sum(a in CATION for a in s)/L
    return [hb_d/L, hb_a/L, (hb_d+hb_a)/L,
            wif, woct, woct - wif,
            vol, charged, arom*fpos]

NEW_NAMES = ["hb_donor_dens","hb_acc_dens","hb_total_dens",
             "ww_interface","ww_octanol","ww_oct_minus_if",
             "mean_volume","charged_frac","cation_pi"]

X_new  = np.array([featurize_interactions(s) for s in df.sequence])
X_full = np.hstack([X, X_new])
print("full feature matrix:", X_full.shape)


def evaluate(features, name):
    for clf, cn in [(LogisticRegression(max_iter=3000), "LogReg"),
                    (RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=0), "RF")]:
        auc = cross_val_score(Pipeline([("s", StandardScaler()), ("c", clf)]),
                              features, y, cv=cv, scoring="roc_auc", n_jobs=-1)
        print(f"  {name:24s}+{cn:8s} AUC={auc.mean():.3f}±{auc.std():.3f}")

print("5-fold CV ROC-AUC:")
evaluate(X,      "Base (26)")
evaluate(X_new,  "NonCovalent only (9)")
evaluate(X_full, "Base+NonCovalent (35)")

nf = pd.DataFrame(X_new, columns=NEW_NAMES); nf["label"] = y
print("\nMeans by class:\n", nf.groupby("label").mean().round(3).T)


subprocess.run("apt-get -qq install -y cd-hit", shell=True, check=True)


import subprocess, re

with open("seqs.fasta", "w") as f:
    for i, s in enumerate(df.sequence):
        f.write(f">{i}\n{s}\n")

subprocess.run("cd-hit -i seqs.fasta -o clust -c 0.4 -n 2 -l 5 -M 0 -T 0",
               shell=True, check=True, capture_output=True)

cluster_of = {}
cid = -1
for line in open("clust.clstr"):
    if line.startswith(">Cluster"):
        cid = int(line.split()[1])
    else:
        m = re.search(r">(\d+)\.\.\.", line)
        if m:
            cluster_of[int(m.group(1))] = cid

missing = [i for i in range(len(df)) if i not in cluster_of]
nxt = (max(cluster_of.values()) + 1) if cluster_of else 0
for i in missing:
    cluster_of[i] = nxt; nxt += 1
if missing:
    print("note: assigned singleton clusters to", len(missing), "sequences")

groups = np.array([cluster_of[i] for i in range(len(df))])
print("sequences:", len(df), "| clusters:", len(set(groups)))


from sklearn.model_selection import StratifiedKFold, GroupKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

rf = lambda: Pipeline([("s", StandardScaler()),
                       ("c", RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=0))])

auc_rand = cross_val_score(rf(), X_full, y,
                           cv=StratifiedKFold(5, shuffle=True, random_state=1),
                           scoring="roc_auc", n_jobs=-1)

auc_grp = cross_val_score(rf(), X_full, y, groups=groups,
                          cv=GroupKFold(5), scoring="roc_auc", n_jobs=-1)

print(f"Random split   AUC = {auc_rand.mean():.3f} ± {auc_rand.std():.3f}")
print(f"Homology split AUC = {auc_grp.mean():.3f} ± {auc_grp.std():.3f}")
print(f"==> Leakage gap = {auc_rand.mean()-auc_grp.mean():.3f}")


from sklearn.linear_model import RidgeCV
from sklearn.model_selection import cross_val_score, KFold

def targets(s):
    s = str(s).upper(); L = len(s)
    arom = sum(a in AROM for a in s)/L; fpos = sum(a in CATION for a in s)/L
    return {
        "net_charge":          net_charge(s),
        "hydrophobic_moment":  muh(s) if 'muh' in globals() else hydrophobic_moment(s),
        "gravy":               sum(KD[a] for a in s)/L,
        "ww_interface":        sum(WW_IF[a] for a in s)/L,
        "ww_octanol":          sum(WW_OCT[a] for a in s)/L,
        "hb_donor_dens":       sum(HB_D[a] for a in s)/L,
        "hb_acc_dens":         sum(HB_A[a] for a in s)/L,
        "cation_pi":           arom*fpos,
        "mean_volume":         sum(VOL[a] for a in s)/L,
        "charged_frac":        sum(a in CHARGED for a in s)/L,
    }

T = pd.DataFrame([targets(s) for s in df.sequence])

X_aac = np.array([[str(s).upper().count(a)/len(str(s)) for a in AA] for s in df.sequence])
print("targets:", T.shape, "| AAC baseline:", X_aac.shape, "| ESM:", X_esm.shape)


import matplotlib.pyplot as plt
cv = KFold(5, shuffle=True, random_state=1)

def probe_r2(features, target):
    m = Pipeline([("s", StandardScaler()), ("r", RidgeCV(alphas=np.logspace(-2, 4, 10)))])
    return cross_val_score(m, features, target, cv=cv, scoring="r2", n_jobs=-1).mean()

rows = []
for col in T.columns:
    r2_esm = probe_r2(X_esm,  T[col].values)
    r2_aac = probe_r2(X_aac,  T[col].values)
    rows.append((col, r2_esm, r2_aac, r2_esm - r2_aac))
res = pd.DataFrame(rows, columns=["property", "R2_ESM", "R2_AAC", "ESM_minus_AAC"])
print(res.round(3).to_string(index=False))

fig, ax = plt.subplots(figsize=(10, 5))
x = np.arange(len(res)); w = 0.38
ax.bar(x - w/2, res.R2_ESM, w, label="ESM-2 embeddings", color="#2a9d8f")
ax.bar(x + w/2, res.R2_AAC, w, label="AAC (composition)", color="#1f3b57")
ax.set_xticks(x); ax.set_xticklabels(res.property, rotation=45, ha="right")
ax.set_ylabel("Probe R²  (5-fold CV)"); ax.set_ylim(0, 1.05)
ax.set_title("What non-covalent biophysics is encoded in ESM-2 embeddings?")
ax.legend(); ax.grid(axis="y", alpha=.3); plt.tight_layout(); plt.show()


def embed_layers(seqs, batch_size=32, max_len=60):
    nlayers = esm.config.num_hidden_layers + 1
    acc = [[] for _ in range(nlayers)]
    for i in range(0, len(seqs), batch_size):
        batch = [str(s).upper() for s in seqs[i:i+batch_size]]
        enc = tok(batch, return_tensors="pt", padding=True, truncation=True, max_length=max_len)
        enc = {k: v.to(device) for k, v in enc.items()}
        with torch.no_grad():
            out = esm(**enc, output_hidden_states=True)
        mask = enc["attention_mask"].unsqueeze(-1)
        for L, h in enumerate(out.hidden_states):
            pooled = (h * mask).sum(1) / mask.sum(1).clamp(min=1)
            acc[L].append(pooled.cpu().numpy())
        if (i // batch_size) % 10 == 0: print(f"  {i+len(batch)}/{len(seqs)}")
    return [np.vstack(a) for a in acc]

layer_emb = embed_layers(df.sequence.tolist())
print("layers:", len(layer_emb), "| each:", layer_emb[0].shape)


prop = T["hydrophobic_moment"].values
r2_by_layer = [probe_r2(emb, prop) for emb in layer_emb]
for L, r in enumerate(r2_by_layer): print(f"layer {L:2d}: R2={r:.3f}")

r2_aac = probe_r2(X_aac, prop)

plt.figure(figsize=(8, 5))
plt.plot(range(len(r2_by_layer)), r2_by_layer, "o-", color="#2a9d8f", lw=2, label="ESM layer")
plt.axhline(r2_aac, ls="--", color="#c1452f", label=f"AAC baseline ({r2_aac:.2f})")
plt.xlabel("ESM-2 layer (0 = input embedding)")
plt.ylabel("Probe R² — hydrophobic moment")
plt.title("Where amphipathicity emerges across ESM-2 depth")
plt.legend(); plt.grid(alpha=.3); plt.tight_layout(); plt.show()


from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
rng = np.random.default_rng(7)

oracle = Pipeline([("s", StandardScaler()),
                   ("c", RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=0))]).fit(X_full, y)

def feats(s):  return np.array(featurize(s) + featurize_interactions(s))
def amp_prob(seqs): return oracle.predict_proba(np.vstack([feats(s) for s in seqs]))[:, 1]

def kmers(s, k=3): return {s[i:i+k] for i in range(len(s)-k+1)}
train_kmers = [kmers(s) for s in df.sequence]
def novelty(s):
    ks = kmers(s)
    return 1 - max((len(ks & t)/len(ks | t)) for t in train_kmers) if ks else 1.0

def fitness(seqs):
    p = amp_prob(seqs)
    mh = np.array([min(hydrophobic_moment(s)/0.4, 1.0) for s in seqs])
    return 0.8*p + 0.2*mh


AA = "ACDEFGHIKLMNPQRSTVWY"
def mutate(s):
    s = list(s); r = rng.random()
    if r < 0.7 and s:                 s[rng.integers(len(s))] = AA[rng.integers(20)]
    elif r < 0.85 and len(s) < 50:    s.insert(rng.integers(len(s)+1), AA[rng.integers(20)])
    elif len(s) > 10:                 del s[rng.integers(len(s))]
    return "".join(s)
def crossover(a, b):
    if len(a) < 2 or len(b) < 2: return a
    c = a[:rng.integers(1, len(a))] + b[rng.integers(1, len(b)):]
    return c[:50] if len(c) > 50 else (c if len(c) >= 10 else a)

amp_seqs = df[df.label == 1].sequence.tolist()
pop = [mutate(mutate(rng.choice(amp_seqs))) for _ in range(200)]
best_hist = []
for gen in range(15):
    fit = fitness(pop); order = np.argsort(fit)[::-1]
    elite = [pop[i] for i in order[:50]]; best_hist.append(float(fit[order[0]]))
    children = []
    while len(children) < 150:
        a, b = rng.choice(len(elite), 2, replace=False)
        c = crossover(elite[a], elite[b])
        if rng.random() < 0.8: c = mutate(c)
        if 10 <= len(c) <= 50: children.append(c)
    pop = elite + children
print("best fitness/gen:", [round(x,3) for x in best_hist])


import matplotlib.pyplot as plt
fit = fitness(pop); order = np.argsort(fit)[::-1]
designs, seen = [], set()
for i in order:
    s = pop[i]
    if s in seen: continue
    seen.add(s)
    if novelty(s) > 0.5 and amp_prob([s])[0] > 0.9: designs.append(s)
print("novel high-confidence designs:", len(designs))

tbl = pd.DataFrame([{"sequence": s, "amp_prob": round(float(amp_prob([s])[0]),3),
                     "net_charge": round(net_charge(s),1), "uH": round(hydrophobic_moment(s),2),
                     "novelty": round(novelty(s),2), "len": len(s)} for s in designs[:10]])
print(tbl.to_string(index=False)); tbl.to_csv("designed_peptides.csv", index=False)

nat = df[df.label==1].sequence.tolist()
fig, ax = plt.subplots(1, 3, figsize=(13, 4))
for a,(fn,t) in zip(ax, [(lambda S:[net_charge(x) for x in S],"Net charge"),
                         (lambda S:[hydrophobic_moment(x) for x in S],"Hydrophobic moment"),
                         (lambda S:amp_prob(S),"Oracle AMP prob")]):
    a.hist(fn(nat), bins=25, alpha=.55, label="natural AMPs", color="#1f3b57", density=True)
    a.hist(fn(designs), bins=25, alpha=.55, label="designed", color="#2a9d8f", density=True)
    a.set_title(t); a.grid(alpha=.3)
ax[0].legend(); plt.tight_layout(); plt.show()


import math
def helical_wheel(seq, ax, title=""):
    seq = str(seq).upper()
    for i, a in enumerate(seq):
        ang = math.radians(100*i); x, y = math.cos(ang), math.sin(ang)
        col = "#c1452f" if EIS[a] > 0 else "#1f3b57"
        ax.scatter(x, y, s=420, color=col, zorder=3, edgecolor="white", linewidth=1.5)
        ax.text(x, y, a, ha="center", va="center", color="white", fontsize=9, zorder=4, fontweight="bold")
        if i: pa = math.radians(100*(i-1)); ax.plot([math.cos(pa),x],[math.sin(pa),y], color="#bbb", lw=1, zorder=1)
    ax.set_xlim(-1.4,1.4); ax.set_ylim(-1.4,1.4); ax.set_aspect("equal"); ax.axis("off"); ax.set_title(title, fontsize=10)

fig, axes = plt.subplots(1, 3, figsize=(12, 4.3))
for ax, s in zip(axes, designs[:3]):
    helical_wheel(s, ax, f"μH={hydrophobic_moment(s):.2f}  q={net_charge(s):+.1f}")
fig.suptitle("Designed peptides — amphipathic segregation (red=hydrophobic, navy=polar/charged)", y=1.02)
plt.tight_layout(); plt.show()


X_esm_train = embed(df.sequence.tolist())
esm_oracle = Pipeline([("s", StandardScaler()),
                       ("c", RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=0))]).fit(X_esm_train, y)
p_esm  = esm_oracle.predict_proba(embed(designs))[:, 1]
p_desc = amp_prob(designs)
print(f"corr(descriptor-oracle, ESM-oracle) on designs: {np.corrcoef(p_desc, p_esm)[0,1]:.3f}")
print(f"designs rated >0.8 by BOTH oracles: {int(((p_desc>0.8)&(p_esm>0.8)).sum())}/{len(designs)}")


def amp_prob_esm(seqs):
    return esm_oracle.predict_proba(embed(list(seqs)))[:, 1]

def fitness_multi(seqs):
    p1 = amp_prob(seqs)
    p2 = amp_prob_esm(seqs)
    mh = np.array([min(hydrophobic_moment(s)/0.4, 1.0) for s in seqs])
    return 0.5*np.minimum(p1, p2) + 0.3*((p1 + p2)/2) + 0.2*mh


pop = [mutate(mutate(rng.choice(amp_seqs))) for _ in range(150)]
for gen in range(12):
    fit = fitness_multi(pop); order = np.argsort(fit)[::-1]
    elite = [pop[i] for i in order[:40]]
    children = []
    while len(children) < 110:
        a, b = rng.choice(len(elite), 2, replace=False)
        c = crossover(elite[a], elite[b])
        if rng.random() < 0.8: c = mutate(c)
        if 10 <= len(c) <= 50: children.append(c)
    pop = elite + children
    print(f"gen {gen}: best={fit[order[0]]:.3f}")


fit = fitness_multi(pop); order = np.argsort(fit)[::-1]
cands, seen = [], set()
for i in order:
    s = pop[i]
    if s not in seen: seen.add(s); cands.append(s)

pc  = amp_prob(cands)
pe  = amp_prob_esm(cands)
nov = np.array([novelty(s) for s in cands])
keep = (pc > 0.9) & (pe > 0.8) & (nov > 0.5)
robust = [cands[i] for i in range(len(cands)) if keep[i]]
print("robust consensus designs:", len(robust))
print(f"corr(descriptor, ESM) on candidates: {np.corrcoef(pc, pe)[0,1]:.3f}  (vs 0.145 before)")

tbl = pd.DataFrame([{"sequence": s,
                     "p_desc": round(float(pc[cands.index(s)]),3),
                     "p_esm":  round(float(pe[cands.index(s)]),3),
                     "charge": round(net_charge(s),1),
                     "uH":     round(hydrophobic_moment(s),2),
                     "novelty":round(novelty(s),2)} for s in robust[:10]])
print(tbl.to_string(index=False)); tbl.to_csv("robust_designs.csv", index=False)


print("=== REVISION ANALYSES (first revision, JCC) ===")

import math, re
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from scipy.stats import pearsonr

DATA_DIR = "."
WONG = dict(orange="#E69F00", sky="#56B4E9", green="#009E73",
            blue="#0072B2", vermillion="#D55E00", purple="#CC79A7")

EIS = {"A":0.62,"R":-2.53,"N":-0.78,"D":-0.90,"C":0.29,"Q":-0.85,"E":-0.74,"G":0.48,
       "H":-0.40,"I":1.38,"L":1.06,"K":-1.50,"M":0.64,"F":1.19,"P":0.12,"S":-0.18,
       "T":-0.05,"W":0.81,"Y":0.26,"V":1.08}
KD = {"A":1.8,"R":-4.5,"N":-3.5,"D":-3.5,"C":2.5,"Q":-3.5,"E":-3.5,"G":-0.4,"H":-3.2,
      "I":4.5,"L":3.8,"K":-3.9,"M":1.9,"F":2.8,"P":-1.6,"S":-0.8,"T":-0.7,"W":-0.9,
      "Y":-1.3,"V":4.2}

def uH(s):
    si = sum(EIS[a]*math.sin(math.radians(100*i)) for i, a in enumerate(s))
    co = sum(EIS[a]*math.cos(math.radians(100*i)) for i, a in enumerate(s))
    return math.sqrt(si*si + co*co)/len(s)

def gravy(s):  return sum(KD[a] for a in s)/len(s)
def charge(s): return sum(1 for a in s if a in "KR") + 0.1*s.count("H") - sum(1 for a in s if a in "DE")

try:
    df = df[["sequence", "label"]].copy()
except NameError:
    df = pd.read_csv(f"{DATA_DIR}/amp_dataset.csv")

df["uH"], df["gravy"], df["charge"] = (df.sequence.map(uH), df.sequence.map(gravy),
                                       df.sequence.map(charge))
print("peptides:", len(df), "| AMP:", int(df.label.sum()), "| non-AMP:", int((1-df.label).sum()))


print("=== Reviewer 2, comment 1: does 40% identity imply biophysical similarity? ===")

id2seq, cur = {}, None
for line in open(f"{DATA_DIR}/seqs.fasta"):
    line = line.strip()
    if line.startswith(">"): cur = line[1:].split()[0]
    elif cur: id2seq[cur] = id2seq.get(cur, "") + line
seq2idx = {s: i for i, s in enumerate(df.sequence)}

cluster_of, cid = {}, None
for line in open(f"{DATA_DIR}/clust.clstr"):
    if line.startswith(">Cluster"):
        cid = int(line.split()[1])
    else:
        m = re.search(r">([^.]+)\.\.\.", line)
        if m and cid is not None and id2seq.get(m.group(1)) in seq2idx:
            cluster_of[seq2idx[id2seq[m.group(1)]]] = cid

df["cluster"] = pd.Series(cluster_of)
multi = df.dropna(subset=["cluster"]).astype({"cluster": int})
multi = multi.groupby("cluster").filter(lambda g: len(g) >= 2)
gm = multi.groupby("cluster")
mixed = gm.label.nunique()
n_mixed, n_pure = int((mixed > 1).sum()), int((mixed == 1).sum())
print(f"multi-member clusters: {gm.ngroups} covering {len(multi)} sequences")
print(f"clusters holding BOTH AMP and non-AMP: {n_mixed} ({100*n_mixed/(n_mixed+n_pure):.1f}%)")

rows, within = [], []
for p, lbl in [("uH", "Hydrophobic moment"), ("charge", "Net charge"), ("gravy", "GRAVY")]:
    g = multi.groupby("cluster")[p]
    ssw = sum(((sub - sub.mean())**2).sum() for _, sub in g)
    pct = 100*ssw/((multi[p] - multi[p].mean())**2).sum()
    within.append(pct)
    rows.append([lbl, round(multi[p].std(ddof=0), 3), round(g.std(ddof=0).mean(), 3),
                 round(pct, 1), round(g.apply(lambda v: v.max()-v.min()).median(), 3)])
tableS3 = pd.DataFrame(rows, columns=["Descriptor", "Total SD", "Mean within-cluster SD",
                                      "Within-cluster variance (%)", "Median within-cluster range"])
print("\nTable S3"); print(tableS3.to_string(index=False))

tot = multi.uH.std(ddof=0)
diffs = np.array([abs(v[i]-v[j]) for _, sub in multi.groupby("cluster")
                  for v in [sub.uH.values] for i in range(len(v)) for j in range(i+1, len(v))])
print(f"\nhomologous pairs differing by >0.5 SD in uH: {100*(diffs > 0.5*tot).mean():.1f}%")

fig, ax = plt.subplots(1, 3, figsize=(10.5, 3.2), dpi=150)
ax[0].bar(["Mixed\n(AMP + non-AMP)", "Single-class"], [n_mixed, n_pure],
          color=[WONG["vermillion"], WONG["sky"]], edgecolor="white", width=.62)
for x, v in enumerate([n_mixed, n_pure]):
    ax[0].text(x, v+3, f"{v}\n({100*v/(n_mixed+n_pure):.1f}%)", ha="center", va="bottom", fontsize=8.5)
ax[0].set_ylabel("Number of clusters"); ax[0].set_ylim(0, max(n_mixed, n_pure)*1.32)
ax[0].set_title("A  Label composition of 40%-identity clusters", loc="left", fontsize=9.5, fontweight="bold")

x = np.arange(3)
ax[1].bar(x, within, color=WONG["orange"], edgecolor="white", width=.6, label="within clusters")
ax[1].bar(x, [100-w for w in within], bottom=within, color=WONG["blue"], edgecolor="white",
          width=.6, label="between clusters")
for i, w in enumerate(within):
    ax[1].text(i, w/2, f"{w:.0f}%", ha="center", va="center", color="white", fontsize=9, fontweight="bold")
ax[1].set_xticks(x); ax[1].set_xticklabels(["Hydrophobic\nmoment", "Net\ncharge", "GRAVY"], fontsize=8.5)
ax[1].set_ylabel("Share of total variance (%)"); ax[1].set_ylim(0, 124)
ax[1].set_yticks([0, 20, 40, 60, 80, 100])
ax[1].legend(fontsize=7.5, loc="upper center", ncol=2, framealpha=0, borderpad=.1)
ax[1].set_title("B  Where the biophysical variance lives", loc="left", fontsize=9.5, fontweight="bold")

ax[2].hist(diffs/tot, bins=40, color=WONG["green"], edgecolor="white")
ax[2].axvline(0.5, color=WONG["vermillion"], lw=1.8, ls="--")
ax[2].text(0.56, ax[2].get_ylim()[1]*0.88,
           f"{100*(diffs > 0.5*tot).mean():.0f}% of homologous\npairs exceed 0.5 SD",
           color=WONG["vermillion"], fontsize=8)
ax[2].set_xlabel("|\u0394 hydrophobic moment| within a cluster  (in units of the global SD)")
ax[2].set_ylabel("Homologous pairs")
ax[2].set_title("C  Divergence between homologous pairs", loc="left", fontsize=9.5, fontweight="bold")
fig.tight_layout(); plt.show()


print("=== Reviewer 2, comment 2: why do two accurate oracles disagree on optimized sequences? ===")

AA = "ACDEFGHIKLMNPQRSTVWY"
HBD = {"R":5,"K":3,"W":1,"N":2,"Q":2,"H":1,"S":1,"T":1,"Y":1,"C":1}
HBA = {"D":2,"E":2,"N":2,"Q":2,"S":1,"T":1,"Y":1,"H":1}
DIX = {a+b: i for i, (a, b) in enumerate((x, y) for x in AA for y in AA)}

def charge_simple(s):
    return sum(1 for a in s if a in "KR") - sum(1 for a in s if a in "DE")

def desc(s):
    L = len(s)
    return [L, gravy(s), uH(s), charge_simple(s), sum(1 for a in s if a in "KRDE")/L,
            sum(HBD.get(a, 0) for a in s)/L, sum(HBA.get(a, 0) for a in s)/L,
            sum(1 for a in s if a in "AVLIMFWC")/L, sum(1 for a in s if a in "FWY")/L]

def dipep(s):
    v = np.zeros(400)
    for i in range(len(s)-1):
        j = DIX.get(s[i:i+2])
        if j is not None: v[j] += 1
    return v/max(len(s)-1, 1)

rng = np.random.default_rng(0)
def mutate(s, n):
    s = list(s)
    for _ in range(n): s[rng.integers(len(s))] = AA[rng.integers(20)]
    return "".join(s)

seqs, y = df.sequence.tolist(), df.label.values
Xd, Xp = np.array([desc(s) for s in seqs]), np.array([dipep(s) for s in seqs])
tr, te = train_test_split(np.arange(len(seqs)), test_size=.3, stratify=y, random_state=0)
A = RandomForestClassifier(400, random_state=0, n_jobs=-1).fit(Xd[tr], y[tr])
B = RandomForestClassifier(400, random_state=1, n_jobs=-1).fit(Xp[tr], y[tr])
pa, pb = A.predict_proba(Xd[te])[:, 1], B.predict_proba(Xp[te])[:, 1]
print(f"oracle A (physicochemical) held-out AUC: {roc_auc_score(y[te], pa):.3f}")
print(f"oracle B (dipeptide)       held-out AUC: {roc_auc_score(y[te], pb):.3f}")

amps = [s for s, l in zip(seqs, y) if l == 1]
mut = [mutate(rng.choice(amps), k) for k in rng.integers(3, 12, 1200)]
ma = A.predict_proba(np.array([desc(s) for s in mut]))[:, 1]
mb = B.predict_proba(np.array([dipep(s) for s in mut]))[:, 1]
hi, hm = (pa > .8) | (pb > .8), (ma > .8) | (mb > .8)
rs = [pearsonr(pa, pb)[0], pearsonr(ma, mb)[0], pearsonr(pa[hi], pb[hi])[0], pearsonr(ma[hm], mb[hm])[0]]
ns = [len(te), len(mut), int(hi.sum()), int(hm.sum())]
names = ["Natural\nfull range", "Off-distribution\nmutants",
         "Natural\nhigh-score band", "Mutants +\nhigh-score band"]
tableS4 = pd.DataFrame({"Evaluation regime": [n.replace("\n", " ") for n in names],
                        "Pearson r": np.round(rs, 3), "n": ns})
print("\nTable S4"); print(tableS4.to_string(index=False))
print("\nthis work, multi-oracle objective: r = 0.545 (single oracle: 0.145)")

fig, ax = plt.subplots(1, 2, figsize=(9.2, 3.3), dpi=150)
cols = [WONG["blue"], WONG["sky"], WONG["orange"], WONG["vermillion"]]
ax[0].bar(np.arange(4), rs, color=cols, edgecolor="white", width=.62)
for i, r in enumerate(rs):
    ax[0].text(i, r + (.03 if r >= 0 else -.07), f"{r:.3f}", ha="center",
               va="bottom" if r >= 0 else "top", fontsize=9, fontweight="bold")
ax[0].axhline(0, color="#888888", lw=.9)
ax[0].axhline(0.545, color=WONG["green"], lw=1.8, ls="--")
ax[0].text(3.42, 0.565, "0.545\nthis work\n(multi-oracle)", color=WONG["green"], fontsize=7.6, ha="right")
ax[0].set_xticks(np.arange(4)); ax[0].set_xticklabels(names, fontsize=8)
ax[0].set_ylabel("Inter-oracle score correlation (r)"); ax[0].set_ylim(-.35, 1.0)
ax[0].set_title("A  Agreement collapses with selection and extrapolation",
                loc="left", fontsize=9.5, fontweight="bold")

ax[1].scatter(pa, pb, s=9, color=WONG["blue"], alpha=.45, label="natural held-out", edgecolor="none")
ax[1].scatter(ma, mb, s=9, color=WONG["vermillion"], alpha=.40, label="off-distribution mutants", edgecolor="none")
ax[1].axvline(.8, color="#888888", lw=.9, ls=":"); ax[1].axhline(.8, color="#888888", lw=.9, ls=":")
ax[1].set_xlabel("Oracle A score (physicochemical)"); ax[1].set_ylabel("Oracle B score (dipeptide)")
ax[1].legend(fontsize=7.5, loc="lower right", framealpha=.95)
ax[1].set_title("B  The band the optimizer explores", loc="left", fontsize=9.5, fontweight="bold")
fig.tight_layout(); plt.show()

